/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import java.util.ArrayList;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexanderbohm
 */
public class ForsaljningsstatistikHattmodeller extends javax.swing.JFrame {
    
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForsaljningsstatistikHattmodeller.class.getName());

    /**
     * Creates new form ForsaljningsstatistikHattmodeller
     */
    public ForsaljningsstatistikHattmodeller(InfDB idb) {
        this.idb = idb;
        initComponents();
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        laddaStatistik();
    }
    
    
    private void laddaStatistik() {
    
    try { 
        
        String sql = "SELECT Hattmodeller.ModellNamn, " 
                + "SUM(IFNULL(Orderrader.Antal, 0)) AS TotaltAntal, " 
                + "SUM(IFNULL(Orderrader.Antal * Orderrader.RadPrisExklMoms, 0)) AS TotalSumma " 
                + "FROM Hattmodeller " +"LEFT JOIN Orderrader ON Hattmodeller.ModellID = Orderrader.ModellID " 
                + "GROUP BY Hattmodeller.ModellID, Hattmodeller.ModellNamn";

        
        ArrayList<HashMap<String, String>> rader = idb.fetchRows(sql);
        
        DefaultTableModel model = (DefaultTableModel) jtStatistik.getModel();
        model.setRowCount(0);
        
        if (rader!= null) {
            for (HashMap<String, String> rad : rader) {
            model.addRow(new Object[]{
                rad.get("ModellNamn"),
                rad.get("TotaltAntal"),
                rad.get("Totalsumma") + " kr"
            });
        }
        }
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Fel vid hämtning av statistik: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtStatistik = new javax.swing.JTable();
        lblForsaljningstatistik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 1990));

        jtStatistik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hattmodell", "Antal sålda", "Total intäkt i kronor"
            }
        ));
        jScrollPane2.setViewportView(jtStatistik);

        jScrollPane1.setViewportView(jScrollPane2);

        lblForsaljningstatistik.setText("Försäljningstatistik för hattmodeller");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(lblForsaljningstatistik)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblForsaljningstatistik)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(() -> new ForsaljningsstatistikHattmodeller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtStatistik;
    private javax.swing.JLabel lblForsaljningstatistik;
    // End of variables declaration//GEN-END:variables
}
