/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Linus
 */
public class HuvudMeny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HuvudMeny.class.getName());
    private InfDB idb;
    
    /**
     * Creates new form HuvudMeny
     */
    public HuvudMeny(InfDB idb) {
        initComponents();
        this.idb = idb;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValkommenText = new javax.swing.JLabel();
        btnMaterial = new javax.swing.JButton();
        btnOrderMeny = new javax.swing.JButton();
        btnLagerfordaModeller = new javax.swing.JButton();
        BTNkundSida = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();
        btnSchemaVy = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommenText.setText("Välkommen till huvudmenyn!");

        btnMaterial.setText("Material");
        btnMaterial.setPreferredSize(new java.awt.Dimension(250, 80));
        btnMaterial.addActionListener(this::btnMaterialActionPerformed);

        btnOrderMeny.setText("Order meny");
        btnOrderMeny.setPreferredSize(new java.awt.Dimension(250, 80));
        btnOrderMeny.addActionListener(this::btnOrderMenyActionPerformed);

        btnLagerfordaModeller.setText("Lagerförda modeller");
        btnLagerfordaModeller.setPreferredSize(new java.awt.Dimension(250, 80));
        btnLagerfordaModeller.addActionListener(this::btnLagerfordaModellerActionPerformed);

        BTNkundSida.setText("Kundsida");
        BTNkundSida.setPreferredSize(new java.awt.Dimension(250, 80));
        BTNkundSida.addActionListener(this::BTNkundSidaActionPerformed);

        btnStatistik.setText("Statistik");
        btnStatistik.setPreferredSize(new java.awt.Dimension(250, 80));
        btnStatistik.addActionListener(this::btnStatistikActionPerformed);

        btnSchemaVy.setText("Schema");
        btnSchemaVy.setPreferredSize(new java.awt.Dimension(250, 80));
        btnSchemaVy.addActionListener(this::btnSchemaVyActionPerformed);

        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new java.awt.Dimension(250, 80));
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNkundSida, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSchemaVy, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLagerfordaModeller, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValkommenText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValkommenText)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrderMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSchemaVy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLagerfordaModeller, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNkundSida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(251, 251, 251)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialActionPerformed
        // TODO add your handling code here:
        
        try {
            new MaterialBestallningsSidan(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
         
        
    }//GEN-LAST:event_btnMaterialActionPerformed

    private void btnOrderMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenyActionPerformed
        // TODO add your handling code here:
        try {
            new OrderMeny(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
          
        
    }//GEN-LAST:event_btnOrderMenyActionPerformed

    private void btnLagerfordaModellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagerfordaModellerActionPerformed
    LagerfordaModeller lagerFonster = new LagerfordaModeller(idb);
    lagerFonster.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnLagerfordaModellerActionPerformed

    private void BTNkundSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkundSidaActionPerformed
    Kundsida ks = new Kundsida(idb);
    ks.setVisible(true);
    
    }//GEN-LAST:event_BTNkundSidaActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        new StatistikDetaljer(idb).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatistikActionPerformed

    private void btnSchemaVyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchemaVyActionPerformed
        SchemaVy sv = new SchemaVy(idb);
        sv.setVisible(true);
    }//GEN-LAST:event_btnSchemaVyActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         LoginMedarbetare lm = new LoginMedarbetare(idb);
        lm.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  break;
                //}
            //}
       // } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new HuvudMeny().setVisible(true));
    {
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkundSida;
    private javax.swing.JButton btnLagerfordaModeller;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMaterial;
    private javax.swing.JButton btnOrderMeny;
    private javax.swing.JButton btnSchemaVy;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JLabel lblValkommenText;
    // End of variables declaration//GEN-END:variables
}
