/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Linus
 */
public class HuvudMeny extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HuvudMeny.class.getName());
    private InfDB idb;
    private String InloggadEmail;

    /**
     * Creates new form HuvudMeny
     */
    public HuvudMeny(InfDB idb, String InloggadEmail) {
        initComponents();
        this.idb = idb;
        this.InloggadEmail = InloggadEmail;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BTNkundSida = new javax.swing.JButton();
        btnMaterial = new javax.swing.JButton();
        btnOrderMeny = new javax.swing.JButton();
        btnSchemaVy = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();
        btnLagerfordaModeller = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblValkommenText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        BTNkundSida.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        BTNkundSida.setText("Kundsida");
        BTNkundSida.setPreferredSize(new java.awt.Dimension(250, 80));
        BTNkundSida.addActionListener(this::BTNkundSidaActionPerformed);
        jPanel1.add(BTNkundSida);

        btnMaterial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnMaterial.setText("Material");
        btnMaterial.setPreferredSize(new java.awt.Dimension(250, 80));
        btnMaterial.addActionListener(this::btnMaterialActionPerformed);
        jPanel1.add(btnMaterial);

        btnOrderMeny.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnOrderMeny.setText("Order meny");
        btnOrderMeny.setPreferredSize(new java.awt.Dimension(250, 80));
        btnOrderMeny.addActionListener(this::btnOrderMenyActionPerformed);
        jPanel1.add(btnOrderMeny);

        btnSchemaVy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSchemaVy.setText("Schema");
        btnSchemaVy.setPreferredSize(new java.awt.Dimension(250, 80));
        btnSchemaVy.addActionListener(this::btnSchemaVyActionPerformed);
        jPanel1.add(btnSchemaVy);

        btnStatistik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnStatistik.setText("Statistik");
        btnStatistik.setPreferredSize(new java.awt.Dimension(250, 80));
        btnStatistik.addActionListener(this::btnStatistikActionPerformed);
        jPanel1.add(btnStatistik);

        btnLagerfordaModeller.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLagerfordaModeller.setText("Lagerförda modeller");
        btnLagerfordaModeller.setPreferredSize(new java.awt.Dimension(250, 80));
        btnLagerfordaModeller.addActionListener(this::btnLagerfordaModellerActionPerformed);
        jPanel1.add(btnLagerfordaModeller);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setText("Logga ut");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        lblValkommenText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        lblValkommenText.setText("Välkommen till huvudmenyn!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 150, 0);
        getContentPane().add(lblValkommenText, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialActionPerformed
        // TODO add your handling code here:

        try {
            new MaterialBestallningsSidan(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }


    }//GEN-LAST:event_btnMaterialActionPerformed

    private void btnOrderMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenyActionPerformed
        // TODO add your handling code here:
        try {
            new OrderMeny(idb, InloggadEmail).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }


    }//GEN-LAST:event_btnOrderMenyActionPerformed

    private void btnLagerfordaModellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagerfordaModellerActionPerformed
        LagerfordaModeller lagerFonster = new LagerfordaModeller(idb);
        lagerFonster.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnLagerfordaModellerActionPerformed

    private void BTNkundSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkundSidaActionPerformed
        Kundsida ks = new Kundsida(idb);
        ks.setVisible(true);

    }//GEN-LAST:event_BTNkundSidaActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        new StatistikDetaljer(idb).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatistikActionPerformed

    private void btnSchemaVyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchemaVyActionPerformed
        SchemaVy sv = new SchemaVy(idb);
        sv.setVisible(true);
    }//GEN-LAST:event_btnSchemaVyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginMedarbetare(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //try {
    //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //  break;
    //}
    //}
    // } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    //logger.log(java.util.logging.Level.SEVERE, null, ex);
    // }
    //</editor-fold>

    /* Create and display the form */
    // java.awt.EventQueue.invokeLater(() -> new HuvudMeny().setVisible(true));
    {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkundSida;
    private javax.swing.JButton btnLagerfordaModeller;
    private javax.swing.JButton btnMaterial;
    private javax.swing.JButton btnOrderMeny;
    private javax.swing.JButton btnSchemaVy;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblValkommenText;
    // End of variables declaration//GEN-END:variables
}
