package hattmakaren2026_9;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ziggy
 */
import oru.inf.InfDB;
import oru.inf.InfException;

import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Kundsida extends javax.swing.JFrame {

    private InfDB idb;
    private java.util.Set<Integer> changedRows = new java.util.HashSet<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kundsida.class.getName());

    /**
     * Creates new form Kundsida
     */
    public Kundsida(InfDB idb) {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.idb = idb;
        visaAllaKunder(); // ← istället för visaAllaKunder() 
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }

    public void visaAllaKunder() {

        ((DefaultTableModel) TBLkund.getModel()).setRowCount(0);

        try {
            String sql = "SELECT KundID, Namn, Epost, Telefon, Adress FROM Kunder";

            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sql);

            if (resultat == null || resultat.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Det finns inga kunder i databasen",
                        "Inga kunder",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (HashMap<String, String> rad : resultat) {
                Object[] row = {
                    rad.get("KundID"),
                    rad.get("Namn"),
                    rad.get("Epost"),
                    rad.get("Telefon"),
                    rad.get("Adress")
                };
                ((DefaultTableModel) TBLkund.getModel()).addRow(row);
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this,
                    "Fel vid hämtning av kunder:\n" + e.getMessage(),
                    "Databasfel",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    public void sokKunder(String sokText) {

        ((DefaultTableModel) TBLkund.getModel()).setRowCount(0);

        if (sokText == null || sokText.trim().isEmpty()) {
            visaAllaKunder();
            return;
        }

        try {

            String sql = "SELECT KundID, Namn, Epost, Telefon, Adress "
                    + "FROM Kunder "
                    + "WHERE KundID LIKE '%" + sokText.trim() + "%' "
                    + "OR Namn LIKE '%" + sokText.trim() + "%' "
                    + "OR Epost LIKE '%" + sokText.trim() + "%' "
                    + "OR Telefon LIKE '%" + sokText.trim() + "%' "
                    + "OR Adress LIKE '%" + sokText.trim() + "%'";

            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sql);

            for (HashMap<String, String> rad : resultat) {
                Object[] row = {
                    rad.get("KundID"),
                    rad.get("Namn"),
                    rad.get("Epost"),
                    rad.get("Telefon"),
                    rad.get("Adress")
                };
                ((DefaultTableModel) TBLkund.getModel()).addRow(row);
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this,
                    "Fel vid sökning:\n" + e.getMessage(),
                    "Databasfel",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void hamtaOchVisa(String sql) {
        try {
            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sql);

            DefaultTableModel model = (DefaultTableModel) TBLkund.getModel();
            model.setRowCount(0);

            for (HashMap<String, String> rad : resultat) {
                model.addRow(new Object[]{
                    rad.get("KundID"),
                    rad.get("Namn"),
                    rad.get("Epost"),
                    rad.get("Telefon"),
                    rad.get("Adress")
                });
            }

        } catch (InfException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNmeny = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLkund = new javax.swing.JTable();
        TXTsokfunktion = new javax.swing.JTextField();
        TXTregNykund = new javax.swing.JButton();
        CBOXsortera = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnTabortKund = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BTNmeny.setText("Tillbaka");
        BTNmeny.addActionListener(this::BTNmenyActionPerformed);

        TBLkund.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kund ID", "Namn", "Epost", "Telefon", "Adress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLkund);

        TXTsokfunktion.addActionListener(this::TXTsokfunktionActionPerformed);
        TXTsokfunktion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTsokfunktionKeyPressed(evt);
            }
        });

        TXTregNykund.setText("Registrera ny kund");
        TXTregNykund.addActionListener(this::TXTregNykundActionPerformed);

        CBOXsortera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Namn A-Ö", "Namn Ö-A", "KundID stigande", "KundID fallande" }));
        CBOXsortera.addActionListener(this::CBOXsorteraActionPerformed);

        jButton1.setText("Spara");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnTabortKund.setText("Ta bort kund");
        btnTabortKund.addActionListener(this::btnTabortKundActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTsokfunktion, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBOXsortera, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNmeny)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTregNykund)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTabortKund, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(TXTsokfunktion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBOXsortera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNmeny)
                    .addComponent(TXTregNykund)
                    .addComponent(btnTabortKund)
                    .addComponent(jButton1))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmenyActionPerformed
        this.dispose(); // stänger Kundsida
    }//GEN-LAST:event_BTNmenyActionPerformed

    private void TXTsokfunktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTsokfunktionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTsokfunktionActionPerformed

    private void CBOXsorteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOXsorteraActionPerformed
        String val = CBOXsortera.getSelectedItem().toString();

        String sql = "";

        switch (val) {
            case "Namn A-Ö":
                sql = "SELECT KundID, Namn, Epost, Telefon, Adress FROM Kunder ORDER BY Namn ASC";
                break;

            case "Namn Ö-A":
                sql = "SELECT KundID, Namn, Epost, Telefon, Adress FROM Kunder ORDER BY Namn DESC";
                break;

            case "KundID stigande":
                sql = "SELECT KundID, Namn, Epost, Telefon, Adress FROM Kunder ORDER BY KundID ASC";
                break;

            case "KundID fallande":
                sql = "SELECT KundID, Namn, Epost, Telefon, Adress FROM Kunder ORDER BY KundID DESC";
                break;
        }

        hamtaOchVisa(sql);
    }//GEN-LAST:event_CBOXsorteraActionPerformed

    private void TXTsokfunktionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTsokfunktionKeyPressed
        String sokText = TXTsokfunktion.getText();
        sokKunder(sokText);
    }//GEN-LAST:event_TXTsokfunktionKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void TXTregNykundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTregNykundActionPerformed

        RegistreraKunder regKunder = new RegistreraKunder(idb, this);
        regKunder.setVisible(true);

    }//GEN-LAST:event_TXTregNykundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (TBLkund.isEditing()) {
            TBLkund.getCellEditor().stopCellEditing();
        }

        DefaultTableModel model = (DefaultTableModel) TBLkund.getModel();

        try {
            for (int row = 0; row < model.getRowCount(); row++) {

                String kundID = model.getValueAt(row, 0).toString();
                String namn = model.getValueAt(row, 1).toString();
                String epost = model.getValueAt(row, 2).toString();
                String telefon = model.getValueAt(row, 3).toString();
                String adress = model.getValueAt(row, 4).toString();

                JTextField tempNamn = new JTextField(namn);
                JTextField tempEpost = new JTextField(epost);
                JTextField tempTelefon = new JTextField(telefon);
                JTextField tempAdress = new JTextField(adress);

                if (Validering.arTom(tempNamn, "Namn saknas på rad " + (row + 1))) {
                    TBLkund.setRowSelectionInterval(row, row);
                    return;
                }
                if (Validering.arTom(tempEpost, "E-post saknas på rad " + (row + 1))) {
                    TBLkund.setRowSelectionInterval(row, row);
                    return;
                }
                if (Validering.arTom(tempAdress, "Adress saknas på rad " + (row + 1))) {
                    TBLkund.setRowSelectionInterval(row, row);
                    return;
                }

                if (!Validering.harForOchEfternamn(tempNamn)) {
                    TBLkund.setRowSelectionInterval(row, row);
                    return;
                }

                if (!Validering.isEpostGiltig(tempEpost)) {
                    TBLkund.setRowSelectionInterval(row, row);
                    return;
                }

                if (!telefon.trim().isEmpty()) {
                    if (!Validering.arGiltigtTelefonnummer(tempTelefon)) {
                        TBLkund.setRowSelectionInterval(row, row);
                        return;
                    }
                }

                String sql = "UPDATE Kunder SET "
                        + "Namn = '" + namn + "', "
                        + "Epost = '" + epost + "', "
                        + "Telefon = '" + telefon + "', "
                        + "Adress = '" + adress + "' "
                        + "WHERE KundID = '" + kundID + "'";

                idb.update(sql);
            }

            JOptionPane.showMessageDialog(this, "Alla ändringar har sparats");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this,
                    "Ett fel uppstod i databasen:\n" + e.getMessage(),
                    "Databasfel",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTabortKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortKundActionPerformed
        int valdRad = TBLkund.getSelectedRow();

        if (valdRad == -1) {
            JOptionPane.showMessageDialog(this, "Markera en kund först.");
            return;
        }

        String kundID = TBLkund.getValueAt(valdRad, 0).toString();
        String namn = TBLkund.getValueAt(valdRad, 1).toString();

        try {
            String kontrollSql = "SELECT KundID FROM Ordrar WHERE KundID = " + kundID;
            String finnsOrder = idb.fetchSingle(kontrollSql);

            if (finnsOrder != null) {
                JOptionPane.showMessageDialog(this,
                        "Kunden kan inte tas bort eftersom den är kopplad till en eller flera ordrar.");
                return;
            }

            int svar = JOptionPane.showConfirmDialog(
                    this,
                    "Vill du ta bort kunden " + namn + " (ID: " + kundID + ")?",
                    "Bekräfta borttagning",
                    JOptionPane.YES_NO_OPTION
            );

            if (svar != JOptionPane.YES_OPTION) {
                return;
            }

            String sql = "DELETE FROM Kunder WHERE KundID = " + kundID;
            idb.delete(sql);

            JOptionPane.showMessageDialog(this, "Kunden togs bort.");
            visaAllaKunder();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this,
                    "Fel vid borttagning:\n" + e.getMessage(),
                    "Databasfel",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }      
    }//GEN-LAST:event_btnTabortKundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNmeny;
    private javax.swing.JComboBox<String> CBOXsortera;
    private javax.swing.JTable TBLkund;
    private javax.swing.JButton TXTregNykund;
    private javax.swing.JTextField TXTsokfunktion;
    private javax.swing.JButton btnTabortKund;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
