/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author lucasbrautigam
 */
public class LagerfordaModeller extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LagerfordaModeller.class.getName());

    /**
     * Creates new form LagerfordaModeller
     */
    public LagerfordaModeller(InfDB idb) {
        this.idb = idb;
        initComponents();
        tftModellID.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
        
        fyllTabell();
    }
    
    private void fyllTabell() {
        try{
                String sql = "SELECT * FROM Hattmodeller";
                ArrayList<HashMap<String, String>> lista = idb.fetchRows(sql);
                
                DefaultTableModel model = (DefaultTableModel)jtHattmodeller.getModel();
                
                model.setRowCount(0);
                
                for(HashMap<String, String> rad : lista){
                    model.addRow(new Object[]{
                        rad.get("ModellID"),
                        rad.get("ModellNamn"),
                        rad.get("Beskrivning"),
                        rad.get("PrisExklMoms"),
                        rad.get("Lagersaldo")
                    });
                }
    } catch (InfException ex){
        JOptionPane.showMessageDialog(null, "Kunde inte ladda tabellen: "+ ex.getMessage());
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        tftModellID = new javax.swing.JTextField();
        tftAntal = new javax.swing.JTextField();
        btnOkaLager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHattmodeller = new javax.swing.JTable();
        lblAntal = new javax.swing.JLabel();
        lblModellID = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        tftModellID.setColumns(10);
        tftModellID.addActionListener(this::tftModellIDActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 44, 0, 0);
        jPanel1.add(tftModellID, gridBagConstraints);

        tftAntal.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 53, 0, 0);
        jPanel1.add(tftAntal, gridBagConstraints);

        btnOkaLager.setText("Öka lager");
        btnOkaLager.addActionListener(this::btnOkaLagerActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 208, 0, 6);
        jPanel1.add(btnOkaLager, gridBagConstraints);

        jtHattmodeller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ModellID", "ModellNamn", "Beskrivning", "PrisExklMoms", "Lagersaldo"
            }
        ));
        jtHattmodeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHattmodellerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHattmodeller);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 579;
        gridBagConstraints.ipady = 308;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(46, 44, 0, 6);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        lblAntal.setText("Antal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 0);
        jPanel1.add(lblAntal, gridBagConstraints);

        lblModellID.setText("ModellID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel1.add(lblModellID, gridBagConstraints);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkaLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkaLagerActionPerformed
    try {
    String modellIDText = tftModellID.getText().trim();
    String antalText = tftAntal.getText().trim();
    // TODO add your han
    if (modellIDText.isEmpty() || antalText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i både ModellID och antal!");
        return;
    }
    
    int modellID = Integer.parseInt(modellIDText);
    int antal = Integer.parseInt(antalText);
    
    if (antal <= 0) {
        JOptionPane.showMessageDialog(this, "Antalet måste vara större än 0");
        return;
    }
    
    String sql = "UPDATE Hattmodeller "
            + "SET Lagersaldo = Lagersaldo + " + antal + " "
            + "WHERE ModellID = " + modellID; 
    
    idb.update(sql);
    JOptionPane.showMessageDialog(this, "Lagersaldot har uppdaterats");
    
    fyllTabell();

    tftModellID.setText("");
    tftAntal.setText("");
    
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "ModellID och antal måste vara siffror.");
    } catch (InfException ex) {
         JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + ex.getMessage());
    }
    
    }//GEN-LAST:event_btnOkaLagerActionPerformed

    private void tftModellIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftModellIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftModellIDActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void jtHattmodellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHattmodellerMouseClicked
    int rad = jtHattmodeller.getSelectedRow();
    String modellID = jtHattmodeller.getValueAt(rad, 0).toString();
    tftModellID.setText(modellID);// TODO add your handling code here:
    }//GEN-LAST:event_jtHattmodellerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new LagerfordaModeller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkaLager;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtHattmodeller;
    private javax.swing.JLabel lblAntal;
    private javax.swing.JLabel lblModellID;
    private javax.swing.JTextField tftAntal;
    private javax.swing.JTextField tftModellID;
    // End of variables declaration//GEN-END:variables
}
