/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author lucasbrautigam
 */
public class LagerfordaModeller extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LagerfordaModeller.class.getName());

    /**
     * Creates new form LagerfordaModeller
     */
    public LagerfordaModeller(InfDB idb) {
        this.idb = idb;
        initComponents();
        tftModellID.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
        
        fyllTabell();
    }
    
    private void fyllTabell() {
        try{
                String sql = "SELECT * FROM Hattmodeller";
                ArrayList<HashMap<String, String>> lista = idb.fetchRows(sql);
                
                DefaultTableModel model = (DefaultTableModel)jtHattmodeller.getModel();
                
                model.setRowCount(0);
                
                for(HashMap<String, String> rad : lista){
                    model.addRow(new Object[]{
                        rad.get("ModellID"),
                        rad.get("ModellNamn"),
                        rad.get("Beskrivning"),
                        rad.get("PrisExklMoms"),
                        rad.get("Lagersaldo")
                    });
                }
    } catch (InfException ex){
        JOptionPane.showMessageDialog(null, "Kunde inte ladda tabellen: "+ ex.getMessage());
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tftModellID = new javax.swing.JTextField();
        tftAntal = new javax.swing.JTextField();
        btnOkaLager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHattmodeller = new javax.swing.JTable();
        lblAntal = new javax.swing.JLabel();
        lblModellID = new javax.swing.JLabel();
        btnMinskaLager = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tftModellID.setColumns(10);
        tftModellID.addActionListener(this::tftModellIDActionPerformed);

        tftAntal.setColumns(10);

        btnOkaLager.setText("Öka lager");
        btnOkaLager.addActionListener(this::btnOkaLagerActionPerformed);

        jtHattmodeller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ModellID", "ModellNamn", "Beskrivning", "PrisExklMoms", "Lagersaldo"
            }
        ));
        jtHattmodeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHattmodellerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHattmodeller);

        lblAntal.setText("Antal");

        lblModellID.setText("ModellID");

        btnMinskaLager.setText("Minska lager");
        btnMinskaLager.addActionListener(this::btnMinskaLagerActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tftModellID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(tftAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblModellID)
                        .addGap(235, 235, 235)
                        .addComponent(lblAntal)))
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOkaLager)
                    .addComponent(btnMinskaLager))
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModellID)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAntal)
                        .addComponent(btnOkaLager)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftModellID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinskaLager)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnTillbaka)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkaLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkaLagerActionPerformed
// 1. Validera att fälten inte är tomma
    if (Validering.arTom(tftModellID, "Välj en modell i tabellen först!")) return;
    if (Validering.arTom(tftAntal, "Ange antal som ska läggas till.")) return;

    // 2. Validera att Antal är ett heltal och är ett positivt tal
    if (!Validering.arHeltal(tftAntal)) return;
    if (!Validering.arPositivtTal(tftAntal)) return;

    try {
        int modellID = Integer.parseInt(tftModellID.getText());
        int antal = Integer.parseInt(tftAntal.getText());

        String sql = "UPDATE Hattmodeller "
                + "SET Lagersaldo = Lagersaldo + " + antal + " "
                + "WHERE ModellID = " + modellID; 

        idb.update(sql);
        JOptionPane.showMessageDialog(this, "Lagersaldot har ökats med " + antal);

        fyllTabell();
        tftAntal.setText("");

    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + ex.getMessage());
    }
    
    }//GEN-LAST:event_btnOkaLagerActionPerformed

    private void tftModellIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftModellIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftModellIDActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void jtHattmodellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHattmodellerMouseClicked
    int rad = jtHattmodeller.getSelectedRow();
    String modellID = jtHattmodeller.getValueAt(rad, 0).toString();
    tftModellID.setText(modellID);// TODO add your handling code here:
    }//GEN-LAST:event_jtHattmodellerMouseClicked

    private void btnMinskaLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinskaLagerActionPerformed
// 1. Validera fält
    if (Validering.arTom(tftModellID, "Välj en modell i tabellen först!")) return;
    if (Validering.arTom(tftAntal, "Ange antal som ska dras bort.")) return;

    // 2. Validera format
    if (!Validering.arHeltal(tftAntal)) return;
    if (!Validering.arPositivtTal(tftAntal)) return;

    try {
        int modellID = Integer.parseInt(tftModellID.getText());
        int antal = Integer.parseInt(tftAntal.getText());

        // Hämta nuvarande saldo för att kontrollera att det inte blir minus
        String nuvarandeSaldoStr = idb.fetchSingle("SELECT Lagersaldo FROM Hattmodeller WHERE ModellID = " + modellID);
        int nuvarandeSaldo = Integer.parseInt(nuvarandeSaldoStr);

        if (nuvarandeSaldo - antal < 0) {
            JOptionPane.showMessageDialog(this, "Fel: Kan inte minska mer än vad som finns i lager! (I lager: " + nuvarandeSaldo + ")");
            return;
        }

        String sql = "UPDATE Hattmodeller "
                    + "SET Lagersaldo = Lagersaldo - " + antal + " "
                    + "WHERE ModellID = " + modellID; 

        idb.update(sql);
        JOptionPane.showMessageDialog(this, "Lagersaldot har minskats!");

        fyllTabell();
        tftAntal.setText("");

    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnMinskaLagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new LagerfordaModeller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinskaLager;
    private javax.swing.JButton btnOkaLager;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtHattmodeller;
    private javax.swing.JLabel lblAntal;
    private javax.swing.JLabel lblModellID;
    private javax.swing.JTextField tftAntal;
    private javax.swing.JTextField tftModellID;
    // End of variables declaration//GEN-END:variables
}
