/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;   

/**
 *
 * @author isakh
 */
public class LoginMedarbetare extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginMedarbetare.class.getName());
   
 
 
    public LoginMedarbetare(InfDB idb) {
    this.idb = idb;
    this.setLocationRelativeTo(null);
    initComponents();
    txtEmail.setText("");
    jpfLosenord.setText("");
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    lblFelmeddelande.setVisible(false);

    btnLoggaIn.addActionListener((java.awt.event.ActionEvent evt) -> {
        loggaIn();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEpost = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        jpfLosenord = new javax.swing.JPasswordField();
        btnLoggaIn = new javax.swing.JButton();
        lblFelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 10, 20));

        lblEpost.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEpost.setText("Epost");
        jPanel1.add(lblEpost);

        txtEmail.setText("otto.dahlman@hattmakarna.se");
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        jPanel1.add(txtEmail);

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLosenord.setText("Lösenord");
        jPanel1.add(lblLosenord);

        jpfLosenord.setText("Hatt_123");
        jpfLosenord.addActionListener(this::jpfLosenordActionPerformed);
        jPanel1.add(jpfLosenord);

        btnLoggaIn.setText("Logga In");
        jPanel1.add(btnLoggaIn);

        lblFelmeddelande.setForeground(new java.awt.Color(255, 51, 51));
        lblFelmeddelande.setText("Felaktigt lösenord eller Epost");
        jPanel1.add(lblFelmeddelande);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jpfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfLosenordActionPerformed

    private void txtEpostActionPerformed(java.awt.event.ActionEvent evt) {                                              
    loggaIn(); // Kör inloggningskontrollen direkt när man trycker Enter
    }                                              
private void loggaIn() {
    String email = txtEmail.getText().trim();
    String losenord = new String(jpfLosenord.getPassword()).trim();

    if (email.isEmpty() || losenord.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fyll i både email och lösenord.");
        return;
    }

    try {
        String kontrollSql = "SELECT COUNT(*) FROM Anstallda "
                + "WHERE Email = '" + email + "' AND Losenord = '" + losenord + "'";

        String antalTraffar = idb.fetchSingle(kontrollSql);

        if (antalTraffar != null && antalTraffar.equals("1")) {

            String infoSql = "SELECT Namn, Roll FROM Anstallda "
                    + "WHERE Email = '" + email + "' AND Losenord = '" + losenord + "'";

            java.util.HashMap<String, String> resultat = idb.fetchRow(infoSql);

            String namn = resultat.get("Namn");
            String roll = resultat.get("Roll");

            boolean arChef = roll != null && roll.equalsIgnoreCase("Chef");


            new HuvudMeny(idb, email).setVisible(true);
            this.dispose();

        } else {
            lblFelmeddelande.setVisible(true);
        }

    } catch (oru.inf.InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Databasfel: " + e.getMessage());
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         /* Create and display the form */
        System.out.println("Inloggningsfönstret startas...");
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfLosenord;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
    private final oru.inf.InfDB idb; 
}
