/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;
/**
 *
 * @author simon
 */
public class MaterialBestallningsSidan extends javax.swing.JFrame {
    private InfDB idb;
    private DefaultTableModel materialModel;
    private DefaultTableModel lagerModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaterialBestallningsSidan.class.getName());

    /**
     * Creates new form MaterialBestallningsSidan
     */
    public MaterialBestallningsSidan(InfDB idb)throws InfException {
this.idb = idb;
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    initMaterialTabell();     
    initMaterialListaTabell(); 
    
    uppdateraTabell();       
    laddaMaterialLista();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnSkapaPdf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterialLista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSokDatum = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLogg = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnTillbakaKnapp = new javax.swing.JButton();
        dcFran = new com.toedter.calendar.JDateChooser();
        dcTill = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMaterial);

        btnSkapaPdf.setText("Beställ material");
        btnSkapaPdf.addActionListener(this::btnSkapaPdfActionPerformed);

        tblMaterialLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMaterialLista);

        jLabel1.setText("Material utifrån ordrar");

        jLabel2.setText("Allt material");

        jLabel3.setText("Från Datum: ");

        jLabel4.setText("Till Datum: ");

        btnSokDatum.setText("Sök");
        btnSokDatum.addActionListener(this::btnSokDatumActionPerformed);

        txtLogg.setEditable(false);
        txtLogg.setColumns(20);
        txtLogg.setRows(5);
        jScrollPane3.setViewportView(txtLogg);

        jLabel5.setText("Välj datumintervall för att se materialbehov");

        btnTillbakaKnapp.setText("Tillbaka");
        btnTillbakaKnapp.addActionListener(this::btnTillbakaKnappActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSkapaPdf)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcTill, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(dcFran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSokDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbakaKnapp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(683, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcFran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dcTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSokDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSkapaPdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(btnTillbakaKnapp)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// </editor-fold>                        

    
    private void initMaterialListaTabell() {
lagerModel = new DefaultTableModel(
        // Här ändrar vi rubriken på sista kolumnen
        new Object[]{"MaterialID", "Material", "Antal i lager", "Antal att beställa", "Beställt senast:"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 3; // Endast "Antal att beställa" ska gå att skriva i
        }
    };
    tblMaterialLista.setModel(lagerModel);
}


    private void laddaMaterialLista() {
try {
        String sql = "SELECT MaterialID, Namn, LagerSaldo, Bestallt, BestallningsDatum FROM Material";
        ArrayList<HashMap<String, String>> materialLista = idb.fetchRows(sql);
        lagerModel.setRowCount(0);

        for (HashMap<String, String> rad : materialLista) {
            String statusCell = "Ej beställt"; 
            

            if ("1".equals(rad.get("Bestallt")) || "true".equalsIgnoreCase(rad.get("Bestallt"))) {
                String datum = rad.get("BestallningsDatum");
                statusCell = "Beställt (" + (datum != null ? datum : "-") + ")";
            }
            
            lagerModel.addRow(new Object[]{
                rad.get("MaterialID"),
                rad.get("Namn"),
                rad.get("LagerSaldo"),
                0.0,
                statusCell
            });
        }
    } catch (Exception e) {
        System.out.println("Lagerfel: " + e.getMessage());
    }

}

 
    private void initMaterialTabell() {
materialModel = new DefaultTableModel(
        new Object[]{"Kundorder", "Material", "Antal material", "Antal i lager", "Antal att beställa"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 4; 
        }
    };
    tblMaterial.setModel(materialModel);
    }
    private List<HashMap<String, String>> hamtaMaterialbehov(List<Integer> orderIds) throws InfException {

    if (orderIds == null || orderIds.isEmpty()) {
        return new ArrayList<>();
    }

    String ids = orderIds.stream()
            .map(String::valueOf)
            .collect(Collectors.joining(", "));

    String sql =
        "SELECT o.OrderID, m.Namn, " +
        "SUM(r.Antal * hm.Antal) AS TotaltBehov, " +
        "m.LagerSaldo " +
        "FROM Ordrar o " +
        "JOIN Orderrader r ON o.OrderID = r.OrderID " +
        "JOIN Hatt_Material hm ON r.ModellID = hm.ModellID " +
        "JOIN Material m ON hm.MaterialID = m.MaterialID " +
        "WHERE o.OrderID IN (" + ids + ") " +
        "GROUP BY o.OrderID, m.MaterialID, m.Namn, m.LagerSaldo";

    return idb.fetchRows(sql);


    }
    private void uppdateraTabell() {
    try {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        
        
        String fran = "";
        String till = "";
        
        if (dcFran.getDate() != null) {
            fran = sdf.format(dcFran.getDate());
        }
        if (dcTill.getDate() != null) {
            till = sdf.format(dcTill.getDate());
        }

        
        StringBuilder sql = new StringBuilder(
            "SELECT OrderID FROM Ordrar " +
            "WHERE Status IN ('Registrerad', 'Tillverkning', 'Under tillverkning') " +
            "AND MaterialBestallt = FALSE "
        );

        if (!fran.isEmpty()) {
            sql.append("AND OrderDatum >= '").append(fran).append(" 00:00:00' ");
        }
        if (!till.isEmpty()) {
            sql.append("AND OrderDatum <= '").append(till).append(" 23:59:59' ");
        }

        ArrayList<HashMap<String, String>> aktivaOrdrar = idb.fetchRows(sql.toString());
        materialModel.setRowCount(0); 

        if (aktivaOrdrar != null && !aktivaOrdrar.isEmpty()) {
            List<Integer> orderIds = aktivaOrdrar.stream()
                    .map(o -> Integer.parseInt(o.get("OrderID")))
                    .collect(Collectors.toList());

            List<HashMap<String, String>> behovsLista = hamtaMaterialbehov(orderIds);

            for (HashMap<String, String> rad : behovsLista) {
                double behov = Double.parseDouble(rad.get("TotaltBehov"));
                double saldo = Double.parseDouble(rad.get("LagerSaldo"));
                double bestall = Math.max(0.0, behov - saldo);

                materialModel.addRow(new Object[]{
                    rad.get("OrderID"),
                    rad.get("Namn"),
                    behov,
                    saldo,
                    bestall
                });
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + e.getMessage());
    }
}
    
    private void btnSkapaPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaPdfActionPerformed
if (tblMaterialLista.isEditing()) tblMaterialLista.getCellEditor().stopCellEditing();
    if (tblMaterial.isEditing()) tblMaterial.getCellEditor().stopCellEditing();

    try {
        // --- STEG 1: VALIDERING (Körs innan vi nollställer loggen) ---
        // Kolla övre tabellen
        for (int i = 0; i < materialModel.getRowCount(); i++) {
            String vardeStr = materialModel.getValueAt(i, 4).toString().trim();
            String namn = materialModel.getValueAt(i, 1).toString();
            if (!vardeStr.equals("0") && !vardeStr.equals("0.0")) {
                if (!Validering.arGiltigBestallning(new JTextField(vardeStr), namn)) return;
            }
        }
        // Kolla nedre tabellen
        for (int i = 0; i < lagerModel.getRowCount(); i++) {
            String vardeStr = lagerModel.getValueAt(i, 3).toString().trim();
            String namn = lagerModel.getValueAt(i, 1).toString();
            if (!vardeStr.equals("0") && !vardeStr.equals("0.0")) {
                if (!Validering.arGiltigBestallning(new JTextField(vardeStr), namn)) return;
            }
        }

        // --- STEG 2: NOLLSTÄLL OCH FÖRBERED LOGG (Sker bara om valideringen gick bra) ---
        txtLogg.setText(""); // Helt tomt först
        txtLogg.setText("BEKRÄFTELSE PÅ BESTÄLLNING\n");
        txtLogg.append("==========================\n");
        
        String nuvarandeDatum = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
        boolean harBestalltNagot = false;

        // --- STEG 3: UTFÖR OCH SKRIV UT ---
        // Övre tabellen
        for (int i = 0; i < materialModel.getRowCount(); i++) {
            double antal = Double.parseDouble(materialModel.getValueAt(i, 4).toString());
            if (antal > 0) {
                String orderID = materialModel.getValueAt(i, 0).toString();
                String namn = materialModel.getValueAt(i, 1).toString();
                String matID = idb.fetchSingle("SELECT MaterialID FROM Material WHERE Namn = '" + namn + "'");
                
                idb.update("UPDATE Material SET Bestallt = TRUE, BestallningsDatum = '" + nuvarandeDatum + "' WHERE MaterialID = " + matID);
                idb.update("UPDATE Ordrar SET MaterialBestallt = TRUE WHERE OrderID = " + orderID);
                
                txtLogg.append("- " + namn + ": " + antal + " st (Order #" + orderID + ")\n");
                harBestalltNagot = true;
            }
        }

        // Nedre tabellen
        for (int i = 0; i < lagerModel.getRowCount(); i++) {
            double antal = Double.parseDouble(lagerModel.getValueAt(i, 3).toString());
            if (antal > 0) {
                String matID = lagerModel.getValueAt(i, 0).toString();
                String namn = lagerModel.getValueAt(i, 1).toString();
                
                idb.update("UPDATE Material SET Bestallt = TRUE, BestallningsDatum = '" + nuvarandeDatum + "' WHERE MaterialID = " + matID);
                
                txtLogg.append("- " + namn + ": " + antal + " st (Lagerbeställning)\n");
                harBestalltNagot = true;
            }
        }

        if (harBestalltNagot) {
            txtLogg.append("==========================\n");
            txtLogg.append("Datum: " + nuvarandeDatum + "\n");
            txtLogg.append("INFO: En textfil har skapats.\n");
            
            sparaOrderTillFil(txtLogg.getText());
            JOptionPane.showMessageDialog(this, "Beställning genomförd!");
            uppdateraTabell();
            laddaMaterialLista();
        } else {
            txtLogg.setText("INGET MATERIAL VALT.\nSkriv in ett antal i kolumnen 'Antal att beställa'.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel: " + e.getMessage());
    }
    }
    private void sparaOrderTillFil(String innehall) {
    String filnamn = "Bestallning_" + java.time.LocalDate.now().toString() + ".txt";
    try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.FileWriter(filnamn, true))) {
        writer.println(innehall);
        writer.println("\n----------------------------\n");
    } catch (Exception e) {
        System.out.println("Kunde inte spara fil: " + e.getMessage());
    }
}
    

    public static class MaterialRad {
        public int orderId;
        public String material;
        public double behov;   
        public double saldo;   
        public double bestall; 

        public MaterialRad(int orderId, String material, double behov, double saldo, double bestall) {
            this.orderId = orderId;
            this.material = material;
            this.behov = behov;
            this.saldo = saldo;
            this.bestall = bestall;
        }
    }//GEN-LAST:event_btnSkapaPdfActionPerformed

    private void btnSokDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokDatumActionPerformed
    uppdateraTabell();
    }//GEN-LAST:event_btnSokDatumActionPerformed

    private void btnTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaKnappActionPerformed
this.dispose();    }//GEN-LAST:event_btnTillbakaKnappActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaPdf;
    private javax.swing.JButton btnSokDatum;
    private javax.swing.JButton btnTillbakaKnapp;
    private com.toedter.calendar.JDateChooser dcFran;
    private com.toedter.calendar.JDateChooser dcTill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTable tblMaterialLista;
    private javax.swing.JTextArea txtLogg;
    // End of variables declaration//GEN-END:variables
}
