/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Linus
 */
public class OrderStatus extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderStatus.class.getName());
    private InfDB idb;

    /**
     * Creates new form OrderStatus
     */
    public OrderStatus(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        fyllRullListaMedKunder();
        
    }

    private void fyllRullListaMedKunder() {
        try {
            ArrayList<String> epostLista = idb.fetchColumn("SELECT Epost FROM Kunder");
        cmbVisaKunder.removeAllItems();
        cmbVisaKunder.addItem("Välj kund (Epost)");
        
        if (epostLista != null) {
            for (String mail : epostLista) {
                cmbVisaKunder.addItem(mail);
            }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOrderStatusRubrik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbVisaKunder = new javax.swing.JComboBox<>();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVisaOrderStatus = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblOrderStatusRubrik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblOrderStatusRubrik.setText("Orderstatus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(lblOrderStatusRubrik, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        cmbVisaKunder.addActionListener(this::cmbVisaKunderActionPerformed);
        jPanel1.add(cmbVisaKunder);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);
        jPanel1.add(btnTillbaka);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(210, 163, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        txtVisaOrderStatus.setEditable(false);
        txtVisaOrderStatus.setColumns(20);
        txtVisaOrderStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVisaOrderStatus.setRows(5);
        jScrollPane1.setViewportView(txtVisaOrderStatus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 327;
        gridBagConstraints.ipady = 281;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(111, 79, 172, 208);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cmbVisaKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVisaKunderActionPerformed
    txtVisaOrderStatus.setText(""); 

        String valdEmail = (String) cmbVisaKunder.getSelectedItem();
        
        
        if (valdEmail == null || valdEmail.isEmpty() || valdEmail.equals("Välj kund (Epost)")) {
            return;
        }

        try {
            
            String fraga = "SELECT Ordrar.OrderID, Ordrar.Status, Ordrar.ArSnabborder, Kunder.Namn "
                         + "FROM Ordrar "
                         + "JOIN Kunder ON Kunder.KundID = Ordrar.KundID "
                         + "WHERE Kunder.Epost = '" + valdEmail + "' "
                         + "ORDER BY Ordrar.OrderID DESC";

            ArrayList<HashMap<String, String>> rader = idb.fetchRows(fraga);

            if (rader != null && !rader.isEmpty()) {
                String kundNamn = rader.get(0).get("Namn");
                StringBuilder sb = new StringBuilder();
                sb.append("ORDERSTATUS FÖR: ").append(kundNamn.toUpperCase()).append("\n");
                sb.append("Email: ").append(valdEmail).append("\n");
                sb.append("==========================================\n\n");

                for (HashMap<String, String> rad : rader) {
                    sb.append("Ordernummer: #").append(rad.get("OrderID")).append("\n");
                    sb.append("Status: ").append(rad.get("Status")).append("\n");
                    
                    String snabb = "Nej";
                    if (rad.get("ArSnabborder").equals("1") || rad.get("ArSnabborder").equalsIgnoreCase("true")) {
                        snabb = "Ja";
                    }
                    sb.append("Prioritet: ").append(snabb).append(" (Snabborder)\n");
                    sb.append("------------------------------------------\n");
                }
                txtVisaOrderStatus.setText(sb.toString());
                txtVisaOrderStatus.setCaretPosition(0); 
            } else {
                txtVisaOrderStatus.setText("Inga ordrar hittades för " + valdEmail);
            }
        } catch (InfException e) {
            System.out.println("Databasfel: " + e.getMessage());
            txtVisaOrderStatus.setText("Ett fel uppstod vid hämtning av status.");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_cmbVisaKunderActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //try {
    //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //if ("Nimbus".equals(info.getName())) {
    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    //}
    //} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    //  logger.log(java.util.logging.Level.SEVERE, null, ex);
    //}
    //</editor-fold>

    /* Create and display the form */
    // java.awt.EventQueue.invokeLater(() -> new OrderStatus().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbVisaKunder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderStatusRubrik;
    private javax.swing.JTextArea txtVisaOrderStatus;
    // End of variables declaration//GEN-END:variables
}
