 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author carlbrandstrom
 */
public class OrderMeny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderMeny.class.getName());
    private InfDB idb;
    private String InloggadEmail; 
    
    /**
     * Creates new form OrderMeny
     */
    public OrderMeny(InfDB idb, String InloggadEmail) throws InfException {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.idb = idb;
        this.InloggadEmail = InloggadEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSkapaKundorder = new javax.swing.JButton();
        btnOrderStatus = new javax.swing.JButton();
        btnSkapaFraktsedel = new javax.swing.JButton();
        btnOrderHistorik = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnAktuellaOrdrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Order Meny");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 584, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 20, 20));

        btnSkapaKundorder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSkapaKundorder.setText("Skapa kundorder");
        btnSkapaKundorder.addActionListener(this::btnSkapaKundorderActionPerformed);
        jPanel1.add(btnSkapaKundorder);

        btnOrderStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnOrderStatus.setText("Orderstatus");
        btnOrderStatus.addActionListener(this::btnOrderStatusActionPerformed);
        jPanel1.add(btnOrderStatus);

        btnSkapaFraktsedel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSkapaFraktsedel.setText("Skapa fraktsedel");
        btnSkapaFraktsedel.addActionListener(this::btnSkapaFraktsedelActionPerformed);
        jPanel1.add(btnSkapaFraktsedel);

        btnOrderHistorik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnOrderHistorik.setText("Orderhistorik");
        btnOrderHistorik.addActionListener(this::btnOrderHistorikActionPerformed);
        jPanel1.add(btnOrderHistorik);

        btnTillbaka.setBackground(new java.awt.Color(204, 204, 204));
        btnTillbaka.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnTillbaka.setText("Tillbaka..");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);
        jPanel1.add(btnTillbaka);

        btnAktuellaOrdrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAktuellaOrdrar.setText("Aktuella ordrar");
        btnAktuellaOrdrar.addActionListener(this::btnAktuellaOrdrarActionPerformed);
        jPanel1.add(btnAktuellaOrdrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.ipady = 171;
        gridBagConstraints.insets = new java.awt.Insets(12, 298, 139, 254);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderHistorikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistorikActionPerformed
        try {
            new OrderHistorik(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnOrderHistorikActionPerformed

    private void btnSkapaKundorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaKundorderActionPerformed
        try {
            new SkapaKundorder(idb, InloggadEmail).setVisible(true);
        } catch(InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSkapaKundorderActionPerformed

    private void btnSkapaFraktsedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaFraktsedelActionPerformed
try {
        String query = "SELECT Ordrar.OrderID, Kunder.Namn FROM Ordrar " +
                       "JOIN Kunder ON Ordrar.KundID = Kunder.KundID";
        java.util.ArrayList<java.util.HashMap<String, String>> allaOrdrar = idb.fetchRows(query);

        if (allaOrdrar != null && !allaOrdrar.isEmpty()) {
            javax.swing.JComboBox<String> orderValjare = new javax.swing.JComboBox<>();
            for (java.util.HashMap<String, String> rad : allaOrdrar) {
                orderValjare.addItem(rad.get("OrderID") + " - " + rad.get("Namn"));
            }

            int val = javax.swing.JOptionPane.showConfirmDialog(this, orderValjare, 
                    "Välj order för fraktsedel", javax.swing.JOptionPane.OK_CANCEL_OPTION);

            if (val == javax.swing.JOptionPane.OK_OPTION) {
                String valtObjekt = (String) orderValjare.getSelectedItem();
                String idStr = valtObjekt.split(" - ")[0];

                String sql = "SELECT Kunder.Namn, Kunder.Adress, Hattmodeller.PrisExklMoms " +
                             "FROM Ordrar " +
                             "JOIN Kunder ON Ordrar.KundID = Kunder.KundID " +
                             "JOIN Orderrader ON Ordrar.OrderID = Orderrader.OrderID " +
                             "JOIN Hattmodeller ON Orderrader.ModellID = Hattmodeller.ModellID " +
                             "WHERE Ordrar.OrderID = " + idStr;

                java.util.HashMap<String, String> data = idb.fetchRow(sql);

                if (data != null) {
                    skapaFraktsedelFil(Integer.parseInt(idStr), data.get("Namn"), data.get("Adress"), data.get("PrisExklMoms"));
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Inga ordrar hittades i systemet.");
        }
    } catch (oru.inf.InfException e) {
        System.out.println("Fel vid hämtning: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSkapaFraktsedelActionPerformed

    private void btnOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderStatusActionPerformed
        try {
            new OrderStatus(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnOrderStatusActionPerformed

    private void btnAktuellaOrdrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktuellaOrdrarActionPerformed

    new AktuellaOrdrar(idb).setVisible(true);
    
    }//GEN-LAST:event_btnAktuellaOrdrarActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed
private void skapaFraktsedelFil(int orderID, String namn, String adress, String prisExkl) {
    String filnamn = "Fraktsedel_Order_" + orderID + ".txt";

    java.util.Random rand = new java.util.Random();

    int slumpNummer = 10000000 + rand.nextInt(90000000); 

    String exportKod = String.valueOf(slumpNummer);
    
    
    
    try (java.io.PrintWriter writer = new java.io.PrintWriter(filnamn, "UTF-8")) {
        double pris = Double.parseDouble(prisExkl);
        double moms = pris * 0.25;
        double totalt = pris + moms;

boolean arExport = adress.toLowerCase().contains("london");
        
          if (arExport) {
    writer.println("======= FRAKTSEDEL (EXPORT) =======");
        } else {
    writer.println("======= FRAKTSEDEL (INRIKES) =======");
                      }
        writer.println("Ordernummer: " + orderID);
        writer.println("Mottagare:   " + namn);
        writer.println("Adress:      " + adress);
        writer.println("-----------------------------------");
        if (arExport) {
            writer.println("Exportkod:   " + exportKod);
        }
        writer.println("Vikt:        0.8 kg");    
        writer.println("Moms (25%):  " + moms + " kr");
        writer.println("Totalpris:   " + totalt + " kr");
        writer.println("===================================");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Success! Filen skapad: " + filnamn);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel: " + e.getMessage());
    }
}
   
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              //  if ("Nimbus".equals(info.getName())) {
                //    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  break;
                //}
            //}
        //} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          //  logger.log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new OrderMeny().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktuellaOrdrar;
    private javax.swing.JButton btnOrderHistorik;
    private javax.swing.JButton btnOrderStatus;
    private javax.swing.JButton btnSkapaFraktsedel;
    private javax.swing.JButton btnSkapaKundorder;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

