/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author carlbrandstrom
 */
public class OrderMeny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderMeny.class.getName());
    private InfDB idb;
    
    /**
     * Creates new form OrderMeny
     */
    public OrderMeny(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSkapaKundorder = new javax.swing.JButton();
        btnOrderHistorik = new javax.swing.JButton();
        btnSkapaFraktsedel = new javax.swing.JButton();
        btnOrderStatus = new javax.swing.JButton();
        btnAktuellaOrdrar = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Order Meny");

        btnSkapaKundorder.setText("Skapa kundorder");
        btnSkapaKundorder.addActionListener(this::btnSkapaKundorderActionPerformed);

        btnOrderHistorik.setText("Orderhistorik");
        btnOrderHistorik.addActionListener(this::btnOrderHistorikActionPerformed);

        btnSkapaFraktsedel.setText("Skapa fraktsedel");
        btnSkapaFraktsedel.addActionListener(this::btnSkapaFraktsedelActionPerformed);

        btnOrderStatus.setText("Orderstatus");
        btnOrderStatus.addActionListener(this::btnOrderStatusActionPerformed);

        btnAktuellaOrdrar.setText("Aktuella ordrar");
        btnAktuellaOrdrar.addActionListener(this::btnAktuellaOrdrarActionPerformed);

        btnTillbaka.setText("Tillbaka..");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrderHistorik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSkapaKundorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSkapaFraktsedel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnTillbaka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnAktuellaOrdrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkapaKundorder)
                    .addComponent(btnSkapaFraktsedel))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderHistorik)
                    .addComponent(btnOrderStatus))
                .addGap(39, 39, 39)
                .addComponent(btnAktuellaOrdrar)
                .addGap(13, 13, 13)
                .addComponent(btnTillbaka)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderHistorikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistorikActionPerformed
        try {
            new OrderHistorik(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnOrderHistorikActionPerformed

    private void btnSkapaKundorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaKundorderActionPerformed
        try {
            new SkapaKundorder(idb).setVisible(true);
        } catch(InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSkapaKundorderActionPerformed

    private void btnSkapaFraktsedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaFraktsedelActionPerformed
//motorn för att skapafraktsedel
        String idStr = javax.swing.JOptionPane.showInputDialog("Ange Order-ID:");
    if (idStr != null && !idStr.isEmpty()) {
        try {
            String sql = "SELECT Kunder.Namn, Kunder.Adress, Hattmodeller.PrisExklMoms " +
                         "FROM Ordrar " +
                         "JOIN Kunder ON Ordrar.KundID = Kunder.KundID " +
                         "JOIN Orderrader ON Ordrar.OrderID = Orderrader.OrderID " +
                         "JOIN Hattmodeller ON Orderrader.ModellID = Hattmodeller.ModellID " +
                         "WHERE Ordrar.OrderID = " + idStr;

            java.util.HashMap<String, String> data = idb.fetchRow(sql);

            if (data != null) {
                skapaFraktsedelFil(Integer.parseInt(idStr), data.get("Namn"), data.get("Adress"), data.get("PrisExklMoms"));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hitta ordern i databasen.");
            }
        } catch (InfException e) {
            System.out.println("Fel vid hämtning: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnSkapaFraktsedelActionPerformed

    private void btnOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderStatusActionPerformed
        try {
            new OrderStatus(idb).setVisible(true);
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnOrderStatusActionPerformed

    private void btnAktuellaOrdrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktuellaOrdrarActionPerformed

    new AktuellaOrdrar(idb).setVisible(true);
    
    }//GEN-LAST:event_btnAktuellaOrdrarActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed
private void skapaFraktsedelFil(int orderID, String namn, String adress, String prisExkl) {
    String filnamn = "Fraktsedel_Order_" + orderID + ".txt";
//metod för slumpmässig fraktkod
    java.util.Random rand = new java.util.Random();

    int slumpNummer = 10000000 + rand.nextInt(90000000); 

    String exportKod = String.valueOf(slumpNummer);
    
    
    
    try (java.io.PrintWriter writer = new java.io.PrintWriter(filnamn, "UTF-8")) {
        double pris = Double.parseDouble(prisExkl);
        double moms = pris * 0.25;
        double totalt = pris + moms;
//tydliggör om ordern är inrikes eller utrikes
//writerprinln metoden skapar fraktsedeln som en txt fil som sparas lokalt
     // Om adressen innehåller "London" eller "UK" så sätter vi export till true
boolean arExport = adress.toLowerCase().contains("london");
        
          if (arExport) {
    writer.println("======= FRAKTSEDEL (EXPORT) =======");
        } else {
    writer.println("======= FRAKTSEDEL (INRIKES) =======");
                      }
        writer.println("Ordernummer: " + orderID);
        writer.println("Mottagare:   " + namn);
        writer.println("Adress:      " + adress);
        writer.println("-----------------------------------");
        if (arExport) {
            writer.println("Exportkod:   " + exportKod);
        }
        writer.println("Vikt:        0.8 kg");    
        writer.println("Moms (25%):  " + moms + " kr");
        writer.println("Totalpris:   " + totalt + " kr");
        writer.println("===================================");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Success! Filen skapad: " + filnamn);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel: " + e.getMessage());
    }
}
   
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              //  if ("Nimbus".equals(info.getName())) {
                //    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  break;
                //}
            //}
        //} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          //  logger.log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new OrderMeny().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktuellaOrdrar;
    private javax.swing.JButton btnOrderHistorik;
    private javax.swing.JButton btnOrderStatus;
    private javax.swing.JButton btnSkapaFraktsedel;
    private javax.swing.JButton btnSkapaKundorder;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

