/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Linus
 */
public class OrderHistorik extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderHistorik.class.getName());
    private InfDB idb;

    /**
     * Creates new form OrderHistorik
     */
    public OrderHistorik(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        fyllRullListaMedKunder();
        
    }

    private void fyllRullListaMedKunder() {
        try {
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbKunder.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOrderHistorikRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorikText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cmbKunder = new javax.swing.JComboBox<>();
        btnVisaHistorik = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblOrderHistorikRubrik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblOrderHistorikRubrik.setText("Orderhistorik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        getContentPane().add(lblOrderHistorikRubrik, gridBagConstraints);

        txtHistorikText.setColumns(20);
        txtHistorikText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHistorikText.setRows(5);
        jScrollPane1.setViewportView(txtHistorikText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 331;
        gridBagConstraints.ipady = 310;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(91, 123, 104, 214);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        cmbKunder.addActionListener(this::cmbKunderActionPerformed);
        jPanel1.add(cmbKunder);

        btnVisaHistorik.setText("Visa historik");
        btnVisaHistorik.addActionListener(this::btnVisaHistorikActionPerformed);
        jPanel1.add(btnVisaHistorik);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);
        jPanel1.add(btnTillbaka);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(186, 154, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKunderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKunderActionPerformed

    private void btnVisaHistorikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaHistorikActionPerformed
                                                     
    txtHistorikText.setText("");

    String valtNamn = (String) cmbKunder.getSelectedItem();
    if (valtNamn == null || valtNamn.isEmpty()) {
        return;
    }
    
    try {
        
        String fraga = "SELECT Ordrar.OrderID, Ordrar.OrderDatum, Ordrar.TotalPrisInclMoms, "
        + "Hattmodeller.ModellNamn, Orderrader.Anpassningstext, Hattmodeller.Farg " 
        + "FROM Ordrar "
        + "JOIN Kunder ON Kunder.KundID = Ordrar.KundID "
        + "JOIN Orderrader ON Ordrar.OrderID = Orderrader.OrderID "
        + "JOIN Hattmodeller ON Orderrader.ModellID = Hattmodeller.ModellID "
        + "WHERE Kunder.Namn = '" + valtNamn + "' "
        + "ORDER BY Ordrar.OrderDatum DESC";

        ArrayList<HashMap<String, String>> rader = idb.fetchRows(fraga);

        if (rader != null && !rader.isEmpty()) {
            txtHistorikText.append("ORDERHISTORIK FÖR: " + valtNamn.toUpperCase() + "\n");
            txtHistorikText.append("==========================================\n");

            String nuvarandeOrderId = "";

            for (HashMap<String, String> rad : rader) {
                String orderId = rad.get("OrderID");
                
          
                if (!orderId.equals(nuvarandeOrderId)) {
                    if (!nuvarandeOrderId.equals("")) {
                        txtHistorikText.append("------------------------------------------\n");
                    }
                    txtHistorikText.append("ORDER #" + orderId + " | Datum: " + rad.get("OrderDatum") + "\n");
                    txtHistorikText.append("Totalpris: " + (rad.get("TotalPrisInclMoms") != null ? rad.get("TotalPrisInclMoms") : "0.00") + " kr inkl. moms\n");
                    txtHistorikText.append("Artiklar:\n");
                    nuvarandeOrderId = orderId;
                }

            
                String hattNamn = rad.get("ModellNamn");
                String dekoration = rad.get("TextDekoration");
                String farg = rad.get("Farg");

                txtHistorikText.append("  > " + hattNamn);
                
         
                if (farg != null && !farg.isEmpty()) {
                    txtHistorikText.append(" (Färg: " + farg + ")");
                }
                if (dekoration != null && !dekoration.isEmpty() && !dekoration.equalsIgnoreCase("null")) {
                    txtHistorikText.append("\n    Dekoration: " + dekoration);
                }
                txtHistorikText.append("\n");
            }
            txtHistorikText.append("==========================================\n");
            
        } else {
            txtHistorikText.setText("Kunden " + valtNamn + " har inga registrerade ordrar.");
        } 
    } catch(InfException e){
        System.out.println("Databasfel: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hämta historik.");
    }

        

    }//GEN-LAST:event_btnVisaHistorikActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaHistorik;
    private javax.swing.JComboBox<String> cmbKunder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderHistorikRubrik;
    private javax.swing.JTextArea txtHistorikText;
    // End of variables declaration//GEN-END:variables
}
