/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Linus
 */
public class OrderStatus extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderStatus.class.getName());
    private InfDB idb;

    /**
     * Creates new form OrderStatus
     */
    public OrderStatus(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        fyllRullListaMedKunder();
        
    }

    private void fyllRullListaMedKunder() {
        try {
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbVisaKunder.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOrderStatusRubrik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbVisaKunder = new javax.swing.JComboBox<>();
        btnVisaStatus = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVisaOrderStatus = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblOrderStatusRubrik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblOrderStatusRubrik.setText("Orderstatus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(lblOrderStatusRubrik, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        cmbVisaKunder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbVisaKunder);

        btnVisaStatus.setText("Visa status");
        btnVisaStatus.addActionListener(this::btnVisaStatusActionPerformed);
        jPanel1.add(btnVisaStatus);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);
        jPanel1.add(btnTillbaka);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(210, 163, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        txtVisaOrderStatus.setColumns(20);
        txtVisaOrderStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVisaOrderStatus.setRows(5);
        jScrollPane1.setViewportView(txtVisaOrderStatus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 327;
        gridBagConstraints.ipady = 281;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(111, 79, 172, 208);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaStatusActionPerformed
        txtVisaOrderStatus.setText("");

        String valtNamn = (String) cmbVisaKunder.getSelectedItem();
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }

        try {
            String fraga = "SELECT Ordrar.Status, Ordrar.ArSnabborder, Ordrar.OrderID "
                    + "FROM Ordrar "
                    + "JOIN Kunder ON Kunder.KundID = Ordrar.KundID "
                    + "WHERE Kunder.Namn = '" + valtNamn + "'";

            ArrayList<HashMap<String, String>> rader = idb.fetchRows(fraga);

            if (rader != null && !rader.isEmpty()) {
                txtVisaOrderStatus.append("Orderstatus för: " + valtNamn + "\n");
                txtVisaOrderStatus.append("-------------------------------\n");

                for (HashMap<String, String> rad : rader) {
                    String status = rad.get("Status");
                    String arSnabborder = rad.get("ArSnabborder");
                    String orderID = rad.get("OrderID");

                    txtVisaOrderStatus.append("OrderID: " + orderID + "\n");
                    txtVisaOrderStatus.append("Status: " + status + "\n");
                    if ("1".equals(arSnabborder) || "true".equalsIgnoreCase(arSnabborder)) {
                        txtVisaOrderStatus.append("Snabborder: Ja \n");
                    }
                    else {
                        txtVisaOrderStatus.append("Snabborder: Nej \n");
                    }
                    txtVisaOrderStatus.append("---------------\n");
                }

            }
            else {
                txtVisaOrderStatus.setText("Kunden " + valtNamn + "har inga registrerade ordrar.");
            }
          
        } catch (InfException e) {
            System.out.println("Databasfel: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hämta status.");
        }
        
    }//GEN-LAST:event_btnVisaStatusActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //try {
    //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //if ("Nimbus".equals(info.getName())) {
    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    //}
    //} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    //  logger.log(java.util.logging.Level.SEVERE, null, ex);
    //}
    //</editor-fold>

    /* Create and display the form */
    // java.awt.EventQueue.invokeLater(() -> new OrderStatus().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaStatus;
    private javax.swing.JComboBox<String> cmbVisaKunder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderStatusRubrik;
    private javax.swing.JTextArea txtVisaOrderStatus;
    // End of variables declaration//GEN-END:variables
}
