/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Linus
 */
public class OrderHistorik extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderHistorik.class.getName());
    private InfDB idb;

    /**
     * Creates new form OrderHistorik
     */
    public OrderHistorik(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        fyllRullListaMedKunder();
        
    }

    private void fyllRullListaMedKunder() {
        try {
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbKunder.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrderHistorikRubrik = new javax.swing.JLabel();
        cmbKunder = new javax.swing.JComboBox<>();
        btnVisaHistorik = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorikText = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOrderHistorikRubrik.setText("Orderhistorik");

        cmbKunder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKunder.addActionListener(this::cmbKunderActionPerformed);

        btnVisaHistorik.setText("Visa historik");
        btnVisaHistorik.addActionListener(this::btnVisaHistorikActionPerformed);

        txtHistorikText.setColumns(20);
        txtHistorikText.setRows(5);
        jScrollPane1.setViewportView(txtHistorikText);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbKunder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTillbaka))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisaHistorik)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOrderHistorikRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblOrderHistorikRubrik)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKunder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisaHistorik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKunderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKunderActionPerformed

    private void btnVisaHistorikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaHistorikActionPerformed
        // TODO add your handling code here:
        txtHistorikText.setText("");

        String valtNamn = (String) cmbKunder.getSelectedItem();
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }
        try {
            String fraga = "SELECT Ordrar.OrderDatum, Ordrar.TotalPrisInclMoms "
                    + "FROM Ordrar "
                    + "JOIN Kunder ON Kunder.KundID = Ordrar.KundID "
                    + "WHERE Kunder.Namn = '" + valtNamn + "'";

            ArrayList<HashMap<String, String>> rader = idb.fetchRows(fraga);

            if (rader != null && !rader.isEmpty()) {
                txtHistorikText.append("Orderhistorik för: " + valtNamn + "\n");
                txtHistorikText.append("-------------------------------\n");

                for (HashMap<String, String> rad : rader) {
                    String datum = rad.get("OrderDatum");
                    // String status = rad.get("Status");
                    String pris = rad.get("TotalPrisInclMoms");

                    if (pris == null) {
                        pris = "0.00";
                    }

                    txtHistorikText.append("Datum: " + datum + "\n");
                    // txtHistorikText.append("Status: " + status + "\n");
                    txtHistorikText.append("Pris: " + pris + "kr inkl.moms\n");
                    txtHistorikText.append("---------------------------\n");

                }
            } else {
                txtHistorikText.setText("Kunden " + valtNamn + "har inga registrerade ordrar.");
               } 
        } catch(InfException e){
                   System.out.println("Databasfel: " + e.getMessage());
                   javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hämta historik.");
                   }
        

    }//GEN-LAST:event_btnVisaHistorikActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaHistorik;
    private javax.swing.JComboBox<String> cmbKunder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderHistorikRubrik;
    private javax.swing.JTextArea txtHistorikText;
    // End of variables declaration//GEN-END:variables
}
