/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import java.util.ArrayList;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alexanderbohm
 */
public class RegistreraKunder extends javax.swing.JFrame {
    private InfDB idb;
    private Kundsida kundsida;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistreraKunder.class.getName());

    /**
     * Creates new form RegistreraKunder
     */
    public RegistreraKunder(InfDB idb, Kundsida kundsida) {
        this.idb = idb;
        this.kundsida = kundsida;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
  
        initComponents();

    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefonnummer = new javax.swing.JTextField();
        BTNtillbaka = new javax.swing.JButton();
        txtNamn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMejladress = new javax.swing.JTextField();
        btnRegNyKund = new javax.swing.JButton();
        txtAdress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 450));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));
        setSize(new java.awt.Dimension(650, 450));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel3.setText("Epost");

        txtTelefonnummer.addActionListener(this::txtTelefonnummerActionPerformed);

        BTNtillbaka.setText("Tillbaka");
        BTNtillbaka.addActionListener(this::BTNtillbakaActionPerformed);

        txtNamn.addActionListener(this::txtNamnActionPerformed);

        jLabel4.setText("Adress");

        jLabel1.setText("Telefon");

        jLabel2.setText("Namn");

        btnRegNyKund.setText("Registrera ny kund");
        btnRegNyKund.addActionListener(this::btnRegNyKundActionPerformed);

        txtAdress.addActionListener(this::txtAdressActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTelefonnummer, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMejladress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegNyKund, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNtillbaka, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMejladress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegNyKund)
                .addGap(18, 18, 18)
                .addComponent(BTNtillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegNyKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNyKundActionPerformed
try {
        if (Validering.arTom(txtNamn, "Namn måste fyllas i!")) return;
        if (!Validering.harForOchEfternamn(txtNamn)) return;
        
        if (Validering.arTom(txtMejladress, "E-post måste fyllas i!")) return;
        if (!Validering.isEpostGiltig(txtMejladress)) return;
        
        if (Validering.arTom(txtTelefonnummer, "Telefonnummer måste fyllas i!")) return;
        if (!Validering.arGiltigtTelefonnummer(txtTelefonnummer)) return;
        
        if (Validering.arTom(txtAdress, "Adress måste fyllas i!")) return;

        String namn = txtNamn.getText().trim();
        String mejladress = txtMejladress.getText().trim();
        String telefon = txtTelefonnummer.getText().trim();
        String adress = txtAdress.getText().trim();

        String nyttID = idb.getAutoIncrement("Kunder", "KundID");
        String sql = "INSERT INTO Kunder (KundID, Namn, Adress, Telefon, Epost) " 
                   + "VALUES (" + nyttID + ", '" + namn + "', '" + adress + "', '" 
                   + telefon + "', '" + mejladress + "')";

        idb.insert(sql);

        if (kundsida != null) {
            kundsida.visaAllaKunder();
        }

        JOptionPane.showMessageDialog(this, "Kunduppgifterna har sparats.");

       
        txtNamn.setText("");
        txtAdress.setText("");
        txtMejladress.setText("");
        txtTelefonnummer.setText("");

    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel uppstod i databasen: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnRegNyKundActionPerformed


    private void BTNtillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNtillbakaActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    private void txtTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonnummerActionPerformed


    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNtillbaka;
    private javax.swing.JButton btnRegNyKund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtMejladress;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
