/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import java.util.ArrayList;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alexanderbohm
 */
public class RegistreraKunder extends javax.swing.JFrame {
    private InfDB idb;
    private Kundsida kundsida;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistreraKunder.class.getName());

    /**
     * Creates new form RegistreraKunder
     */
    public RegistreraKunder(InfDB idb, Kundsida kundsida) {
        this.idb = idb;
        this.kundsida = kundsida;
  
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefonnummer = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtMejladress = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        btnRegNyKund = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNtillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTelefonnummer.addActionListener(this::txtTelefonnummerActionPerformed);

        txtNamn.addActionListener(this::txtNamnActionPerformed);

        txtAdress.addActionListener(this::txtAdressActionPerformed);

        btnRegNyKund.setText("Registrera ny kund");
        btnRegNyKund.addActionListener(this::btnRegNyKundActionPerformed);

        jLabel1.setText("Telefonnummer");

        jLabel2.setText("Namn");

        jLabel3.setText("Mejl");

        jLabel4.setText("Adress");

        BTNtillbaka.setText("Tillbaka");
        BTNtillbaka.addActionListener(this::BTNtillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegNyKund)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                        .addComponent(txtMejladress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTelefonnummer, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNamn, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(1137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNtillbaka)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNtillbaka)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMejladress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(74, 74, 74)
                .addComponent(btnRegNyKund)
                .addContainerGap(610, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonnummerActionPerformed

    private void btnRegNyKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNyKundActionPerformed
    try {
        String namn = txtNamn.getText().trim();
        String mejladress = txtMejladress.getText().trim();
        String telefon = txtTelefonnummer.getText().trim();
        String adress = txtAdress.getText().trim();
               
       if (namn.isEmpty() || adress.isEmpty() || mejladress.isEmpty() || telefon.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Alla fält måste fyllas i!");
       }
       String nyttID = idb.getAutoIncrement("Kunder", "KundID");
       String sql = "INSERT INTO Kunder (KundID, Namn, Adress, Telefon, Epost) " + "VALUES (" + nyttID + " ,'"
        + namn + "', '" 
        + adress + "', '" 
        + telefon + "', '" 
        + mejladress + "')";
       
       
       idb.insert(sql);
       
       if (kundsida != null) {
            kundsida.visaAllaKunder();
        }
       
       JOptionPane.showMessageDialog(null, "Ny kund har registrerats!");
       
       txtNamn.setText(""); txtAdress.setText(""); txtMejladress.setText(""); txtTelefonnummer.setText("");
       
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Gick inte att spara i databasen. Kontrollera uppgifterna.");
    }
    }//GEN-LAST:event_btnRegNyKundActionPerformed


    private void BTNtillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNtillbakaActionPerformed

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed


    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNtillbaka;
    private javax.swing.JButton btnRegNyKund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtMejladress;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
