/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JTextField;


/**
 *
 * @author rodaf
 */
public class SchemaVy extends javax.swing.JFrame {
    private InfDB idb;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchemaVy.class.getName());

    /**
     * Creates new form SchemaVy
     */
    public SchemaVy(InfDB idb) {
        initComponents();
        this.idb = idb;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        jtSchema.setDefaultRenderer(Object.class, new SchemaFargsattare());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtSchema = new javax.swing.JTable();
        btnVisaSchema = new javax.swing.JButton();
        btnPlaneraPass = new javax.swing.JButton();
        btnTillbakaKnapp = new javax.swing.JButton();
        btnRedigeraPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtSchema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Anställda", "Måndag", "Tisdag", "Onsdag", "Torsdag", "Fredag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtSchema.setGridColor(new java.awt.Color(204, 204, 204));
        jtSchema.setIntercellSpacing(new java.awt.Dimension(1, 1));
        jtSchema.setRowHeight(60);
        jtSchema.setRowSelectionAllowed(false);
        jtSchema.setShowGrid(true);
        jtSchema.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jtSchema);

        btnVisaSchema.setText("Visa schema...");
        btnVisaSchema.addActionListener(this::btnVisaSchemaActionPerformed);

        btnPlaneraPass.setText("Planera pass....");
        btnPlaneraPass.addActionListener(this::btnPlaneraPassActionPerformed);

        btnTillbakaKnapp.setText("Tillbaka......");
        btnTillbakaKnapp.addActionListener(this::btnTillbakaKnappActionPerformed);

        btnRedigeraPass.setText("Redigera pass...");
        btnRedigeraPass.addActionListener(this::btnRedigeraPassActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisaSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaneraPass, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRedigeraPass, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVisaSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaneraPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRedigeraPass, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaSchemaActionPerformed

    String[] veckor = {
        "Vecka 16 (2026-04-13 - 2026-04-17)",
        "Vecka 17 (2026-04-20 - 2026-04-24)",
    };

    JComboBox<String> cbVeckor = new JComboBox<>(veckor);
    int option = JOptionPane.showConfirmDialog(this, cbVeckor, "Välj vecka att visa", JOptionPane.OK_CANCEL_OPTION);

    if (option == JOptionPane.OK_OPTION) {
        String valdVecka = cbVeckor.getSelectedItem().toString();
        
        // 3. Plocka ut startdatumet från strängen (vi klipper ut det som står mellan parenteserna)
        // Ett enkelt sätt är att använda substring eller bara en if-sats
        String startDatum = "";
        String slutDatum = "";
        
        if (valdVecka.contains("Vecka 16")) {
            startDatum = "2026-04-13";
            slutDatum = "2026-04-17";
        } else if (valdVecka.contains("Vecka 17")) {
            startDatum = "2026-04-20";
            slutDatum = "2026-04-24";
        } // ... och så vidare för de andra veckorna
        fyllSchemaTabell(startDatum, slutDatum);
    }

    }//GEN-LAST:event_btnVisaSchemaActionPerformed

    private void btnPlaneraPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaneraPassActionPerformed
try {
        ArrayList<String> anstallda = idb.fetchColumn("SELECT Namn FROM Anstallda");
        ArrayList<String> ordrar = idb.fetchColumn("SELECT OrderID FROM Ordrar");
        ordrar.add(0, "Inget (Allmänt arbete)"); // Möjliggör pass utan order

        JComboBox<String> cbPersonal = new JComboBox<>(anstallda.toArray(new String[0]));
        JComboBox<String> cbOrder = new JComboBox<>(ordrar.toArray(new String[0]));
        JTextField txtDatum = new JTextField("2026-04-13"); // Förifyll gärna
        JTextField txtTimmar = new JTextField("8");
        JTextField txtAktivitet = new JTextField("Beskrivning...");

        Object[] formular = {
            "Vem ska utföra arbetet?:", cbPersonal,
            "Vilken order gäller det?:", cbOrder,
            "Datum (ÅÅÅÅ-MM-DD):", txtDatum,
            "Antal timmar:", txtTimmar,
            "Vad ska göras?:", txtAktivitet
        };

        int svar = JOptionPane.showConfirmDialog(this, formular, "Planera nytt arbetspass", JOptionPane.OK_CANCEL_OPTION);

        if (svar == JOptionPane.OK_OPTION) {
            // Hämta AnstalldID baserat på det valda namnet
            String valtNamn = cbPersonal.getSelectedItem().toString();
            String anstID = idb.fetchSingle("SELECT AnstalldID FROM Anstallda WHERE Namn = '" + valtNamn + "'");
            
            // Hantera OrderID (blir NULL om man valde "Inget")
            String valtOrderID = cbOrder.getSelectedItem().toString();
            String orderValue = valtOrderID.contains("Inget") ? "NULL" : valtOrderID;

            // 4. Skicka in i databasen
            String sql = "INSERT INTO Arbetspass (AnstalldID, OrderID, Datum, Timmar, Aktivitet) VALUES ("
                    + anstID + ", " + orderValue + ", '" + txtDatum.getText() + "', " 
                    + txtTimmar.getText() + ", '" + txtAktivitet.getText() + "')";

            idb.insert(sql);
            
            // 5. UPPDATERA SCHEMAT DIREKT
            // Här anropar vi din befintliga metod med de datum som är aktiva just nu
            // (Tips: Du kan hämta dessa från dina datum-fält eller rullistan)
            fyllSchemaTabell("2026-04-13", "2026-04-17"); 
            
            JOptionPane.showMessageDialog(this, "Passet har sparats och schemat är uppdaterat!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kunde inte spara passet: " + e.getMessage());
    }

    }//GEN-LAST:event_btnPlaneraPassActionPerformed

    private void btnTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaKnappActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaKnappActionPerformed

    private void btnRedigeraPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraPassActionPerformed
int valdRad = jtSchema.getSelectedRow();
    if (valdRad == -1) {
        JOptionPane.showMessageDialog(this, "Markera en person i listan först!");
        return;
    }

    try {
        String anstalldNamn = jtSchema.getValueAt(valdRad, 0).toString();
        String anstalldID = idb.fetchSingle("SELECT AnstalldID FROM Anstallda WHERE Namn = '" + anstalldNamn + "'");

        String sql = "SELECT PassID, Datum, Aktivitet FROM Arbetspass WHERE AnstalldID = " + anstalldID;
        ArrayList<HashMap<String, String>> passLista = idb.fetchRows(sql);

        if (passLista == null || passLista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inga pass hittades för " + anstalldNamn);
            return;
        }
        JComboBox<String> cbValjPass = new JComboBox<>();
        for (HashMap<String, String> pass : passLista) {
            cbValjPass.addItem(pass.get("PassID") + ": " + pass.get("Datum") + " - " + pass.get("Aktivitet"));
        }

        int val = JOptionPane.showConfirmDialog(this, cbValjPass, "Välj pass", JOptionPane.OK_CANCEL_OPTION);

        if (val == JOptionPane.OK_OPTION) {
            String passID = cbValjPass.getSelectedItem().toString().split(":")[0];
            
            HashMap<String, String> nuvarande = idb.fetchRow("SELECT * FROM Arbetspass WHERE PassID = " + passID);

            JTextField txtNyAktivitet = new JTextField(nuvarande.get("Aktivitet"));
            JTextField txtNyttDatum = new JTextField(nuvarande.get("Datum"));
            JTextField txtNyaTimmar = new JTextField(nuvarande.get("Timmar"));

            Object[] editForm = {"Aktivitet:", txtNyAktivitet, "Datum:", txtNyttDatum, "Timmar:", txtNyaTimmar};
            Object[] alternativ = {"Spara", "TA BORT", "Avbryt"};
            
            int handling = JOptionPane.showOptionDialog(this, editForm, "Hantera pass",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, alternativ, alternativ[0]);

            if (handling == JOptionPane.YES_OPTION) { // SPARA
                idb.update("UPDATE Arbetspass SET Aktivitet='" + txtNyAktivitet.getText() + "', Datum='" + txtNyttDatum.getText() + "', Timmar=" + txtNyaTimmar.getText() + " WHERE PassID=" + passID);
            } else if (handling == JOptionPane.NO_OPTION) { // TA BORT
                idb.delete("DELETE FROM Arbetspass WHERE PassID = " + passID);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRedigeraPassActionPerformed

    private void fyllSchemaTabell(String startDatum, String slutDatum) {
   try {
        DefaultTableModel model = (DefaultTableModel) jtSchema.getModel();
        model.setRowCount(0); 
        
        String sqlAnstallda = "SELECT AnstalldID, Namn FROM Anstallda";
        ArrayList<HashMap<String, String>> listaAnstallda = idb.fetchRows(sqlAnstallda);

        if (listaAnstallda != null) {
            for (HashMap<String, String> anstalld : listaAnstallda) {
                String id = anstalld.get("AnstalldID");
                Object[] radData = new Object[6];
                radData[0] = anstalld.get("Namn");

                String sqlPass = "SELECT Datum, Aktivitet, OrderID, Timmar FROM Arbetspass " +
                                 "WHERE AnstalldID = " + id + " " +
                                 "AND Datum BETWEEN '" + startDatum + "' AND '" + slutDatum + "'";
                
                ArrayList<HashMap<String, String>> passData = idb.fetchRows(sqlPass);

                if (passData != null) {
                    for (HashMap<String, String> pass : passData) {
                        String datum = pass.get("Datum");
                        String aktivitet = pass.get("Aktivitet");
                        String order = (pass.get("OrderID") != null) ? " (#" + pass.get("OrderID") + ")" : "";
                        String timmar = pass.get("Timmar") != null ? pass.get("Timmar") : "0";
                        
                        int kolumn = beraknaKolumnIndex(startDatum, datum);
                        
                        if (kolumn >= 1 && kolumn <= 5) {
                            String nyttPassInfo = aktivitet + order + " [" + timmar + "h]";
                          
                            if (radData[kolumn] == null) {
                              
                                radData[kolumn] = nyttPassInfo;
                            } else {

                                String befintligText = radData[kolumn].toString();

                                if (!befintligText.startsWith("<html>")) {
                                    radData[kolumn] = "<html>" + befintligText + "<br>" + nyttPassInfo + "</html>";
                                } else {
                                    String städadText = befintligText.replace("</html>", "");
                                    radData[kolumn] = städadText + "<br>" + nyttPassInfo + "</html>";
                                }
                            }
                        }
                    }
                }
                model.addRow(radData);
            }
        }
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + ex.getMessage());
    }
}
    
    
    private int beraknaKolumnIndex(String startStr, String passStr) {
    try {
        // Gör om textsträngarna till riktiga datum-objekt
        java.time.LocalDate start = java.time.LocalDate.parse(startStr);
        java.time.LocalDate pass = java.time.LocalDate.parse(passStr);
        
        // Räknar ut hur många dagar det skiljer mellan startdatumet och passets datum
        long skillnad = java.time.temporal.ChronoUnit.DAYS.between(start, pass);
        
        // Returnera skillnaden + 1 (eftersom kolumn 0 är "Personal")
        return (int) skillnad + 1;
    } catch (Exception e) {
        return -1; // Om något går fel (t.ex. felaktigt datumformat)
    }
}
    
  public class SchemaFargsattare extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        c.setBackground(Color.WHITE);
        c.setForeground(Color.BLACK);

        if (column > 0 && value != null) {
            String cellText = value.toString();
            int totalaTimmar = extraheraOchSummeraTimmar(cellText);

            if (totalaTimmar >= 7) {
                c.setBackground(new Color(255, 153, 153)); // Röd
            } else if (totalaTimmar >= 4) {
                c.setBackground(new Color(255, 255, 153)); // Gul
            } else if (totalaTimmar > 0) {
                c.setBackground(new Color(153, 255, 153)); // Grön
            }
        }
        if (isSelected) {
            c.setBackground(table.getSelectionBackground());
            c.setForeground(table.getSelectionForeground());
        }
        return c;
    }

    private int extraheraOchSummeraTimmar(String text) {
        int summa = 0;
        try {
            String[] delar = text.split("\\[");
            for (int i = 1; i < delar.length; i++) {
                StringBuilder siffra = new StringBuilder();
                for (char tecken : delar[i].toCharArray()) {
                    if (Character.isDigit(tecken)) {
                        siffra.append(tecken);
                    } else {
                        break; 
                    }
                }
                if (siffra.length() > 0) {
                    summa += Integer.parseInt(siffra.toString());
                }
            }
        } catch (Exception e) {
            System.out.println("Fel vid summering: " + e.getMessage());
        }
        return summa;
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaneraPass;
    private javax.swing.JButton btnRedigeraPass;
    private javax.swing.JButton btnTillbakaKnapp;
    private javax.swing.JButton btnVisaSchema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtSchema;
    // End of variables declaration//GEN-END:variables
}
