
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Creates new form SkapaKundorder
 */
public class SkapaKundorder extends javax.swing.JFrame {

    private InfDB idb;

    private double totaltPris = 0.0;
    private double styckPrisHatt = 0.0;

    public SkapaKundorder(InfDB idb) throws InfException {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.idb = idb;

        LocalDate dagensDatum = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        txtDatum.setText(dagensDatum.format(formatter));
        txtDatum.setEditable(false);
        
        fyllRulllistaMedKunder();
        fyllRullistaMedHattar();
        fyllAlternativ();

    }

    private void fyllRulllistaMedKunder() {
        try {
            cmbValjKund.removeAllItems();
            cmbValjKund.addItem("Välj kund");
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbValjKund.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private void fyllRullistaMedHattar() {
        try {
            cmbHatt.removeAllItems();
            ArrayList<String> namnLista = idb.fetchColumn("select ModellNamn from Hattmodeller");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbHatt.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }

    private void fyllAlternativ() {
        cmbFarg.addItem("Svart");
        cmbFarg.addItem("Vit");
        cmbFarg.addItem("Blå");
        cmbFarg.addItem("Röd");
        cmbFarg.addItem("Grön");
        cmbFarg.addItem("Gul");
        cmbFarg.addItem("Brun");
        cmbFarg.addItem("Natur");

        cmbTyg.addItem("Ullfilt");
        cmbTyg.addItem("Kaninfilt");
        cmbTyg.addItem("Läder");
        cmbTyg.addItem("Linne");
        cmbTyg.addItem("Tweed");
        cmbTyg.addItem("Toquillastrå");

        cmbStorlek.addItem("S");
        cmbStorlek.addItem("M");
        cmbStorlek.addItem("L");
        cmbStorlek.addItem("XL");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbValjKund = new javax.swing.JComboBox();
        btnPaborjaOrder = new javax.swing.JButton();
        cmbHatt = new javax.swing.JComboBox<>();
        lblHattmodell = new javax.swing.JLabel();
        txtKundId = new javax.swing.JTextField();
        lblKundIdForOrder = new javax.swing.JLabel();
        lblFraktadress = new javax.swing.JLabel();
        txtFraktadress = new javax.swing.JTextField();
        txtAntalHattar = new javax.swing.JTextField();
        btnLaggTillIOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        cmbFarg = new javax.swing.JComboBox<>();
        cmbTyg = new javax.swing.JComboBox<>();
        cmbStorlek = new javax.swing.JComboBox<>();
        lblVäljAntal = new javax.swing.JLabel();
        txtPrisExklMoms = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkSnabborder = new javax.swing.JCheckBox();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skapa en ny kundorder");

        cmbValjKund.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kurt Lupton", "Mikael Maskerad", "Lotta Larsson", "Sofia Sömmerska", "Erik Export" }));
        cmbValjKund.addActionListener(this::cmbValjKundActionPerformed);

        btnPaborjaOrder.setText("Registrera Order");
        btnPaborjaOrder.addActionListener(this::btnPaborjaOrderActionPerformed);

        cmbHatt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHatt.addActionListener(this::cmbHattActionPerformed);

        lblHattmodell.setText("Lagerförda hattmodeller");

        txtKundId.setEditable(false);
        txtKundId.addActionListener(this::txtKundIdActionPerformed);

        lblKundIdForOrder.setText("KundId för ordern");

        lblFraktadress.setText("Fraktadress");

        txtFraktadress.setText("Fraktadress");

        txtAntalHattar.addActionListener(this::txtAntalHattarActionPerformed);

        btnLaggTillIOrder.setText("Lägg till i order");
        btnLaggTillIOrder.addActionListener(this::btnLaggTillIOrderActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hattmodell", "Färg", "Tyg", "Storlek", "Antal", "Snabborder"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Hattar i order");

        txtDatum.setText("Datum");

        lblDatum.setText("Datum");

        cmbFarg.addActionListener(this::cmbFargActionPerformed);

        lblVäljAntal.setText("Välj antal");

        txtPrisExklMoms.addActionListener(this::txtPrisExklMomsActionPerformed);

        jLabel2.setText("Pris exkl moms:");

        chkSnabborder.setText("Snabborder");
        chkSnabborder.addActionListener(this::chkSnabborderActionPerformed);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(cmbTyg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHattmodell, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(cmbFarg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblKundIdForOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKundId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLaggTillIOrder)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblVäljAntal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAntalHattar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(chkSnabborder))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPaborjaOrder)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTillbaka)
                            .addComponent(txtPrisExklMoms, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblKundIdForOrder))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKundId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDatum))
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFraktadress))
                    .addComponent(txtFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lblVäljAntal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHattmodell)
                    .addComponent(txtAntalHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSnabborder))
                .addGap(18, 18, 18)
                .addComponent(btnLaggTillIOrder)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrisExklMoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnPaborjaOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnPaborjaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaborjaOrderActionPerformed
        try {
        // 1. Hämta data för huvudordern
        String kundID = txtKundId.getText();
        String fraktAdress = txtFraktadress.getText();
        String datum = txtDatum.getText();
        // Kontrollera att en kund är vald
        if (kundID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Välj en kund först!");
            return;
        }
 
        // 2. Kontrollera om någon hatt i tabellen är en snabborder
        int arSnabborder = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Ordern är tom. Lägg till hattar först!");
            return;
        }
 
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 5).toString().equals("Ja")) {
                arSnabborder = 1;
                break;
            }
        }
 
        // 3. Skapa huvudordern i tabellen 'Ordrar'
        // Vi hämtar totalpriset från er pris-variabel (kom ihåg att ersätta , med .)
        String totalPrisStr = txtPrisExklMoms.getText().replace(",", ".");
        double totalPrisInklMoms = Double.parseDouble(totalPrisStr) * 1.25;
 
        String orderSql = "INSERT INTO Ordrar (KundID, OrderDatum, Status, ArSnabborder, FraktAdress, TotalPrisInclMoms) "
                + "VALUES (" + kundID + ", '" + datum + "', 'Registrerad', " + arSnabborder + ", '" + fraktAdress + "', " + totalPrisInklMoms + ")";
        idb.insert(orderSql);
 
        // 4. Hämta det OrderID som just skapades
        String nyttOrderID = idb.fetchSingle("SELECT MAX(OrderID) FROM Ordrar");
 
        // 5. LOOPA igenom tabellen för att spara varje rad
        for (int i = 0; i < model.getRowCount(); i++) {
            String hattNamn = model.getValueAt(i, 0).toString();
            String farg = model.getValueAt(i, 1).toString();
            String tyg = model.getValueAt(i, 2).toString();
            String storlek = model.getValueAt(i, 3).toString();
            String antal = model.getValueAt(i, 4).toString();
 
            // Hämta ModellID för hatten
            String modellID = idb.fetchSingle("SELECT ModellID FROM Hattmodeller WHERE ModellNamn = '" + hattNamn + "'");
            // Bygg anpassningstexten (User Story: Anpassning)
            String anpassning = "Färg: " + farg + ", Tyg: " + tyg + ", Storlek: " + storlek;
 
            // Spara raden i 'Orderrader'
            String radSql = "INSERT INTO Orderrader (OrderID, ModellID, Antal, Anpassningstext) "
                    + "VALUES (" + nyttOrderID + ", " + modellID + ", " + antal + ", '" + anpassning + "')";
            idb.insert(radSql);
        }
 
        // 6. Avsluta och gå till nästa fönster
        JOptionPane.showMessageDialog(this, "Order #" + nyttOrderID + " har registrerats!");
        
 
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Databastillgång misslyckades: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnPaborjaOrderActionPerformed

    private void txtKundIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKundIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKundIdActionPerformed

    private void cmbFargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFargActionPerformed
        // TODO
    }//GEN-LAST:event_cmbFargActionPerformed

    private void cmbHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHattActionPerformed
        String valtNamn = (String) cmbHatt.getSelectedItem();

        // 1. Viktigt: Gör inget om vi bara har rensat boxen
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }

        try {
            String fraga = "SELECT Farg, Tyg, Storlek, PrisExklMoms FROM Hattmodeller WHERE ModellNamn = '" + valtNamn + "'";
            java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                // Vi hämtar datan först
                String f = rad.get("Farg");
                String t = rad.get("Tyg");
                String s = rad.get("Storlek");

                String p = rad.get("PrisExklMoms");
                if (p != null) {
                    styckPrisHatt = Double.parseDouble(p);
                }

                // 2. Tvinga Swing att uppdatera rutorna på "rätt" sätt
                javax.swing.SwingUtilities.invokeLater(() -> {
                    // Töm och fyll Färg
                    // cmbFarg.removeAllItems();
                    cmbFarg.setSelectedItem(f != null ? f : "Saknas");

                    // Töm och fyll Tyg
                    // cmbTyg.removeAllItems();
                    cmbTyg.setSelectedItem(t != null ? t : "Saknas");

                    // Töm och fyll Storlek
                    // cmbStorlek.removeAllItems();
                    cmbStorlek.setSelectedItem(s != null ? s : "Saknas");

                    // 3. Tvinga rutorna att ritas om (Repaint)
                    cmbFarg.revalidate();
                    cmbFarg.repaint();
                    cmbTyg.revalidate();
                    cmbTyg.repaint();
                    cmbStorlek.revalidate();
                    cmbStorlek.repaint();
                });

                System.out.println("Data insatt i boxarna: " + f + ", " + t + ", " + s);
            }
        } catch (InfException e) {
            System.out.println("Fel: " + e.getMessage());
        }

    }//GEN-LAST:event_cmbHattActionPerformed

    private void cmbValjKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValjKundActionPerformed
        String valtNamn = (String) cmbValjKund.getSelectedItem();
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }
        try {
            String fraga = "select KundID, Adress FROM Kunder WHERE Namn = '" + valtNamn + "'";
            java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                txtKundId.setText(rad.get("KundID"));
                txtFraktadress.setText(rad.get("Adress"));
            }

        } catch (InfException e) {
            System.out.println("Fel: " + e.getMessage());
        }

    }//GEN-LAST:event_cmbValjKundActionPerformed

    private void txtAntalHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntalHattarActionPerformed

    }//GEN-LAST:event_txtAntalHattarActionPerformed

    private void btnLaggTillIOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillIOrderActionPerformed
        String snabborderText = "Nej";
        if (chkSnabborder.isSelected()) {
            snabborderText = "Ja";
        }
        String antalStr = txtAntalHattar.getText().trim();
        int antal = antalStr.isEmpty() ? 1 : Integer.parseInt(antalStr);
        String hattModell = (String) cmbHatt.getSelectedItem();
        String tyg = (String) cmbTyg.getSelectedItem();
        String farg = (String) cmbFarg.getSelectedItem();
        String storlek = (String) cmbStorlek.getSelectedItem();

        // Räknar priset på valda hattar och plussar på totalen
        double radPris = styckPrisHatt * antal;
        if (chkSnabborder.isSelected()) {
           radPris *= 0.8; 
        }
        totaltPris += radPris;
        

        // Uppdaterar textfältet
        txtPrisExklMoms.setText(String.format("%.2f", totaltPris));

        // 2. Lägg till raden i tabellen
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Vi sparar priset som en formaterad sträng i tabellen
        model.addRow(new Object[]{hattModell, tyg, farg, storlek, antal, snabborderText});


    }//GEN-LAST:event_btnLaggTillIOrderActionPerformed

    private void txtPrisExklMomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrisExklMomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrisExklMomsActionPerformed

    private void chkSnabborderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSnabborderActionPerformed
        
    }//GEN-LAST:event_chkSnabborderActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    //public static void main(String args[]) {
    // java.awt.EventQueue.invokeLater(new Runnable() {S
    //  public void run() {
    // new SkapaKundorder().setVisible(true);
    //}
    //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillIOrder;
    private javax.swing.JButton btnPaborjaOrder;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JCheckBox chkSnabborder;
    private javax.swing.JComboBox<String> cmbFarg;
    private javax.swing.JComboBox<String> cmbHatt;
    private javax.swing.JComboBox<String> cmbStorlek;
    private javax.swing.JComboBox<String> cmbTyg;
    private javax.swing.JComboBox cmbValjKund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblFraktadress;
    private javax.swing.JLabel lblHattmodell;
    private javax.swing.JLabel lblKundIdForOrder;
    private javax.swing.JLabel lblVäljAntal;
    private javax.swing.JTextField txtAntalHattar;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtFraktadress;
    private javax.swing.JTextField txtKundId;
    private javax.swing.JTextField txtPrisExklMoms;
    // End of variables declaration//GEN-END:variables
}
