
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Creates new form SkapaKundorder
 */
public class SkapaKundorder extends javax.swing.JFrame {

    private InfDB idb;

    private double totaltPris = 0.0;
    private double styckPrisHatt = 0.0;

    public SkapaKundorder(InfDB idb) throws InfException {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.idb = idb;

        LocalDate dagensDatum = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        txtDatum.setText(dagensDatum.format(formatter));
        txtDatum.setEditable(false);
        
        fyllRulllistaMedKunder();
        fyllRullistaMedHattar();
        fyllAlternativ();

    }

    private void fyllRulllistaMedKunder() {
        try {
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbValjKund.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private void fyllRullistaMedHattar() {
        try {
            cmbHatt.removeAllItems();
            ArrayList<String> namnLista = idb.fetchColumn("select ModellNamn from Hattmodeller");

            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbHatt.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }

    private void fyllAlternativ() {
        cmbFarg.addItem("Svart");
        cmbFarg.addItem("Vit");
        cmbFarg.addItem("Blå");
        cmbFarg.addItem("Röd");
        cmbFarg.addItem("Grön");
        cmbFarg.addItem("Gul");
        cmbFarg.addItem("Brun");
        cmbFarg.addItem("Natur");

        cmbTyg.addItem("Ullfilt");
        cmbTyg.addItem("Kaninfilt");
        cmbTyg.addItem("Läder");
        cmbTyg.addItem("Linne");
        cmbTyg.addItem("Tweed");
        cmbTyg.addItem("Toquillastrå");

        cmbStorlek.addItem("S");
        cmbStorlek.addItem("M");
        cmbStorlek.addItem("L");
        cmbStorlek.addItem("XL");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbValjKund = new javax.swing.JComboBox();
        btnPaborjaOrder = new javax.swing.JButton();
        cmbHatt = new javax.swing.JComboBox<>();
        lblHattmodell = new javax.swing.JLabel();
        txtKundId = new javax.swing.JTextField();
        lblKundIdForOrder = new javax.swing.JLabel();
        lblFraktadress = new javax.swing.JLabel();
        txtFraktadress = new javax.swing.JTextField();
        txtAntalHattar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        cmbFarg = new javax.swing.JComboBox<>();
        cmbTyg = new javax.swing.JComboBox<>();
        cmbStorlek = new javax.swing.JComboBox<>();
        lblVäljAntal = new javax.swing.JLabel();
        txtPrisExklMoms = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkSnabborder = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skapa Kundorder");

        cmbValjKund.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kurt Lupton", "Mikael Maskerad", "Lotta Larsson", "Sofia Sömmerska", "Erik Export" }));
        cmbValjKund.addActionListener(this::cmbValjKundActionPerformed);

        btnPaborjaOrder.setText("Registrera Order");
        btnPaborjaOrder.addActionListener(this::btnPaborjaOrderActionPerformed);

        cmbHatt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHatt.addActionListener(this::cmbHattActionPerformed);

        lblHattmodell.setText("Lagerförda hattmodeller");

        txtKundId.setEditable(false);
        txtKundId.addActionListener(this::txtKundIdActionPerformed);

        lblKundIdForOrder.setText("KundId för ordern");

        lblFraktadress.setText("Fraktadress");

        txtFraktadress.setText("Fraktadress");

        txtAntalHattar.addActionListener(this::txtAntalHattarActionPerformed);

        jButton1.setText("Lägg till i order");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hattmodell", "Färg", "Tyg", "Storlek", "Antal", "Snabborder"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Välj kund");

        jLabel5.setText("Hattar i order");

        txtDatum.setText("Datum");

        lblDatum.setText("Datum");

        cmbFarg.addActionListener(this::cmbFargActionPerformed);

        lblVäljAntal.setText("Välj antal");

        txtPrisExklMoms.addActionListener(this::txtPrisExklMomsActionPerformed);

        jLabel2.setText("Pris exkl moms:");

        chkSnabborder.setText("Snabborder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)))
                        .addComponent(txtFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(cmbTyg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHattmodell, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(cmbFarg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblKundIdForOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKundId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblVäljAntal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAntalHattar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(chkSnabborder))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPaborjaOrder)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addComponent(txtPrisExklMoms, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKundIdForOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKundId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDatum))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFraktadress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFraktadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(lblVäljAntal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHattmodell)
                    .addComponent(txtAntalHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSnabborder))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrisExklMoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnPaborjaOrder)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnPaborjaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaborjaOrderActionPerformed

        
    }//GEN-LAST:event_btnPaborjaOrderActionPerformed

    private void txtKundIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKundIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKundIdActionPerformed

    private void cmbFargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFargActionPerformed
        // TODO
    }//GEN-LAST:event_cmbFargActionPerformed

    private void cmbHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHattActionPerformed
        String valtNamn = (String) cmbHatt.getSelectedItem();

        // 1. Viktigt: Gör inget om vi bara har rensat boxen
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }

        try {
            String fraga = "SELECT Farg, Tyg, Storlek, PrisExklMoms FROM Hattmodeller WHERE ModellNamn = '" + valtNamn + "'";
            java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                // Vi hämtar datan först
                String f = rad.get("Farg");
                String t = rad.get("Tyg");
                String s = rad.get("Storlek");

                String p = rad.get("PrisExklMoms");
                if (p != null) {
                    styckPrisHatt = Double.parseDouble(p);
                }

                // 2. Tvinga Swing att uppdatera rutorna på "rätt" sätt
                javax.swing.SwingUtilities.invokeLater(() -> {
                    // Töm och fyll Färg
                    // cmbFarg.removeAllItems();
                    cmbFarg.setSelectedItem(f != null ? f : "Saknas");

                    // Töm och fyll Tyg
                    // cmbTyg.removeAllItems();
                    cmbTyg.setSelectedItem(t != null ? t : "Saknas");

                    // Töm och fyll Storlek
                    // cmbStorlek.removeAllItems();
                    cmbStorlek.setSelectedItem(s != null ? s : "Saknas");

                    // 3. Tvinga rutorna att ritas om (Repaint)
                    cmbFarg.revalidate();
                    cmbFarg.repaint();
                    cmbTyg.revalidate();
                    cmbTyg.repaint();
                    cmbStorlek.revalidate();
                    cmbStorlek.repaint();
                });

                System.out.println("Data insatt i boxarna: " + f + ", " + t + ", " + s);
            }
        } catch (InfException e) {
            System.out.println("Fel: " + e.getMessage());
        }

    }//GEN-LAST:event_cmbHattActionPerformed

    private void cmbValjKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValjKundActionPerformed
        String valtNamn = (String) cmbValjKund.getSelectedItem();
        if (valtNamn == null || valtNamn.isEmpty()) {
            return;
        }
        try {
            String fraga = "select KundID, Adress FROM Kunder WHERE Namn = '" + valtNamn + "'";
            java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                txtKundId.setText(rad.get("KundID"));
                txtFraktadress.setText(rad.get("Adress"));
            }

        } catch (InfException e) {
            System.out.println("Fel: " + e.getMessage());
        }

    }//GEN-LAST:event_cmbValjKundActionPerformed

    private void txtAntalHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntalHattarActionPerformed

    }//GEN-LAST:event_txtAntalHattarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String snabborderText = "Nej";
        if (chkSnabborder.isSelected()) {
            snabborderText = "Ja";
        }
        String antalStr = txtAntalHattar.getText().trim();
        int antal = antalStr.isEmpty() ? 1 : Integer.parseInt(antalStr);
        String hattModell = (String) cmbHatt.getSelectedItem();
        String tyg = (String) cmbTyg.getSelectedItem();
        String farg = (String) cmbFarg.getSelectedItem();
        String storlek = (String) cmbStorlek.getSelectedItem();

        // Räknar priset på valda hattar och plussar på totalen
        double radPris = styckPrisHatt * antal;
        totaltPris += radPris;

        // Uppdaterar textfältet
        txtPrisExklMoms.setText(String.format("%.2f", totaltPris));

        // 2. Lägg till raden i tabellen
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Vi sparar priset som en formaterad sträng i tabellen
        model.addRow(new Object[]{hattModell, tyg, farg, storlek, antal, snabborderText});


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrisExklMomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrisExklMomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrisExklMomsActionPerformed

    //public static void main(String args[]) {
    // java.awt.EventQueue.invokeLater(new Runnable() {S
    //  public void run() {
    // new SkapaKundorder().setVisible(true);
    //}
    //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaborjaOrder;
    private javax.swing.JCheckBox chkSnabborder;
    private javax.swing.JComboBox<String> cmbFarg;
    private javax.swing.JComboBox<String> cmbHatt;
    private javax.swing.JComboBox<String> cmbStorlek;
    private javax.swing.JComboBox<String> cmbTyg;
    private javax.swing.JComboBox cmbValjKund;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblFraktadress;
    private javax.swing.JLabel lblHattmodell;
    private javax.swing.JLabel lblKundIdForOrder;
    private javax.swing.JLabel lblVäljAntal;
    private javax.swing.JTextField txtAntalHattar;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtFraktadress;
    private javax.swing.JTextField txtKundId;
    private javax.swing.JTextField txtPrisExklMoms;
    // End of variables declaration//GEN-END:variables
}
