/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import java.util.ArrayList;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexanderbohm
 */
public class StatistikKund extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatistikKund.class.getName());

    /**
     * Creates new form StatistikKund
     */
    public StatistikKund(InfDB idb) {
        this.idb = idb;
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        laddaStatistikKund();
    }
    
    private void laddaStatistikKund() {
        try {
            String sql = "SELECT Kunder.Epost, " + 
                         "SUM(IFNULL(Orderrader.Antal, 0)) AS AntalHattar, " +
                         "SUM(IFNULL(Orderrader.Antal * Orderrader.RadPrisExklMoms, 0)) AS SummaSpenderat " + 
                         "FROM Kunder " +
                         "LEFT JOIN Ordrar ON Kunder.KundID = Ordrar.KundID " + 
                         "LEFT JOIN Orderrader ON Ordrar.OrderID = Orderrader.OrderID " + 
                         "GROUP BY Kunder.Epost"; 

            ArrayList<HashMap<String, String>> rader = idb.fetchRows(sql);
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
            if (rader != null) {
                for (HashMap<String, String> rad : rader) {
                    String epost = rad.get("Epost");
                    String antal = rad.get("AntalHattar");
                    String pengar = rad.get("SummaSpenderat");
                    
                    if (antal == null) antal = "0";
                    if (pengar == null) pengar = "0";
                    
                    model.addRow(new Object[]{
                        epost,
                        antal,
                        pengar + " kr"
                    });
                }
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Fel vid hämntning av kundstatistik: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtKundStatistik = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Epost", "Antal Hattar", "Total spendering"
            }
        ));
        jtKundStatistik.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jtKundStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jtKundStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new StatistikKund().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jtKundStatistik;
    // End of variables declaration//GEN-END:variables
}
