/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfDB;
/**
 *
 * @author alexanderbohm
 */
public class StatistikMeny extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatistikMeny.class.getName());

    /**
     * Creates new form StatistikMeny
     */
    public StatistikMeny(InfDB idb) {
        this.idb = idb;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatistik = new javax.swing.JLabel();
        btnHattar = new javax.swing.JButton();
        btnKunder = new javax.swing.JButton();
        btnTid = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatistik.setText("Välj statistik");

        btnHattar.setText("Försäljningsstatistik per modell");
        btnHattar.addActionListener(this::btnHattarActionPerformed);

        btnKunder.setText("Försäljningsstatistik per kund");
        btnKunder.addActionListener(this::btnKunderActionPerformed);

        btnTid.setText("Försäljningsstatistik (år, månad, kvartal)");

        btnTillbaka.setText("Tillbaka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(btnHattar)
                        .addGap(18, 18, 18)
                        .addComponent(btnKunder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(lblStatistik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnTid)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblStatistik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHattar)
                    .addComponent(btnKunder)
                    .addComponent(btnTid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHattarActionPerformed
    new ForsaljningsstatistikHattmodeller(idb).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHattarActionPerformed

    private void btnKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKunderActionPerformed
    new StatistikKund(idb).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKunderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new StatistikMeny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHattar;
    private javax.swing.JButton btnKunder;
    private javax.swing.JButton btnTid;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblStatistik;
    // End of variables declaration//GEN-END:variables
}
